<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/dns/fakedns/fakedns.proto

namespace GPBMetadata\App\Dns\Fakedns;

class Fakedns
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE6\x02\x0A\x1Dapp/dns/fakedns/fakedns.proto\x12\x1Av2ray.core.app.dns.fakedns\"G\x0A\x0BFakeDnsPool\x12\x0F\x0A\x07ip_pool\x18\x01 \x01(\x09\x12\x0F\x0A\x07lruSize\x18\x02 \x01(\x03:\x16\x82\xB5\x18\x12\x0A\x07service\x12\x07fakeDns\"g\x0A\x10FakeDnsPoolMulti\x126\x0A\x05pools\x18\x01 \x03(\x0B2'.v2ray.core.app.dns.fakedns.FakeDnsPool:\x1B\x82\xB5\x18\x17\x0A\x07service\x12\x0CfakeDnsMultiBo\x0A\x1Ecom.v2ray.core.app.dns.fakednsP\x01Z.github.com/v2fly/v2ray-core/v5/app/dns/fakedns\xAA\x02\x1AV2Ray.Core.App.Dns.Fakednsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

