<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/http/simplified/config.proto

namespace V2ray\Core\Proxy\Http\Simplified;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.http.simplified.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 1;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     */
    protected $port = 0;
    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 3;</code>
     */
    protected $h1_skip_wait_for_reply = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Common\Net\IPOrDomain $address
     *     @type int $port
     *     @type bool $h1_skip_wait_for_reply
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Http\Simplified\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @return \V2ray\Core\Common\Net\IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 1;</code>
     * @param \V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 3;</code>
     * @return bool
     */
    public function getH1SkipWaitForReply()
    {
        return $this->h1_skip_wait_for_reply;
    }

    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setH1SkipWaitForReply($var)
    {
        GPBUtil::checkBool($var);
        $this->h1_skip_wait_for_reply = $var;

        return $this;
    }

}

