<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/http/config.proto

namespace GPBMetadata\Proxy\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\ServerSpec::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x80\x04\x0A\x17proxy/http/config.proto\x12\x15v2ray.core.proxy.http\"-\x0A\x07Account\x12\x10\x0A\x08username\x18\x01 \x01(\x09\x12\x10\x0A\x08password\x18\x02 \x01(\x09\"\xC8\x01\x0A\x0CServerConfig\x12\x13\x0A\x07timeout\x18\x01 \x01(\x0DB\x02\x18\x01\x12C\x0A\x08accounts\x18\x02 \x03(\x0B21.v2ray.core.proxy.http.ServerConfig.AccountsEntry\x12\x19\x0A\x11allow_transparent\x18\x03 \x01(\x08\x12\x12\x0A\x0Auser_level\x18\x04 \x01(\x0D\x1A/\x0A\x0DAccountsEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"j\x0A\x0CClientConfig\x12:\x0A\x06server\x18\x01 \x03(\x0B2*.v2ray.core.common.protocol.ServerEndpoint\x12\x1E\x0A\x16h1_skip_wait_for_reply\x18\x02 \x01(\x08B`\x0A\x19com.v2ray.core.proxy.httpP\x01Z)github.com/v2fly/v2ray-core/v5/proxy/http\xAA\x02\x15V2Ray.Core.Proxy.Httpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

