<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proxyman/command/command.proto

namespace V2ray\Core\App\Proxyman\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.proxyman.command.AddInboundRequest</code>
 */
class AddInboundRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     */
    protected $inbound = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\InboundHandlerConfig $inbound
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     * @return \V2ray\Core\InboundHandlerConfig|null
     */
    public function getInbound()
    {
        return $this->inbound;
    }

    public function hasInbound()
    {
        return isset($this->inbound);
    }

    public function clearInbound()
    {
        unset($this->inbound);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.InboundHandlerConfig inbound = 1;</code>
     * @param \V2ray\Core\InboundHandlerConfig $var
     * @return $this
     */
    public function setInbound($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\InboundHandlerConfig::class);
        $this->inbound = $var;

        return $this;
    }

}

