<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/config.proto

namespace V2ray\Core\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * SocketConfig is options to be applied on network sockets.
 *
 * Generated from protobuf message <code>v2ray.core.transport.internet.SocketConfig</code>
 */
class SocketConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     *
     * Generated from protobuf field <code>uint32 mark = 1;</code>
     */
    protected $mark = 0;
    /**
     * TFO is the state of TFO settings.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     */
    protected $tfo = 0;
    /**
     * TProxy is for enabling TProxy socket option.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     */
    protected $tproxy = 0;
    /**
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     *
     * Generated from protobuf field <code>bool receive_original_dest_address = 4;</code>
     */
    protected $receive_original_dest_address = false;
    /**
     * Generated from protobuf field <code>bytes bind_address = 5;</code>
     */
    protected $bind_address = '';
    /**
     * Generated from protobuf field <code>uint32 bind_port = 6;</code>
     */
    protected $bind_port = 0;
    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 7;</code>
     */
    protected $accept_proxy_protocol = false;
    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_interval = 8;</code>
     */
    protected $tcp_keep_alive_interval = 0;
    /**
     * Generated from protobuf field <code>uint32 tfo_queue_length = 9;</code>
     */
    protected $tfo_queue_length = 0;
    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_idle = 10;</code>
     */
    protected $tcp_keep_alive_idle = 0;
    /**
     * Generated from protobuf field <code>string bind_to_device = 11;</code>
     */
    protected $bind_to_device = '';
    /**
     * Generated from protobuf field <code>int64 rx_buf_size = 12;</code>
     */
    protected $rx_buf_size = 0;
    /**
     * Generated from protobuf field <code>int64 tx_buf_size = 13;</code>
     */
    protected $tx_buf_size = 0;
    /**
     * Generated from protobuf field <code>bool force_buf_size = 14;</code>
     */
    protected $force_buf_size = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $mark
     *           Mark of the connection. If non-zero, the value will be set to SO_MARK.
     *     @type int $tfo
     *           TFO is the state of TFO settings.
     *     @type int $tproxy
     *           TProxy is for enabling TProxy socket option.
     *     @type bool $receive_original_dest_address
     *           ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     *           option. This option is for UDP only.
     *     @type string $bind_address
     *     @type int $bind_port
     *     @type bool $accept_proxy_protocol
     *     @type int $tcp_keep_alive_interval
     *     @type int $tfo_queue_length
     *     @type int $tcp_keep_alive_idle
     *     @type string $bind_to_device
     *     @type int|string $rx_buf_size
     *     @type int|string $tx_buf_size
     *     @type bool $force_buf_size
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     *
     * Generated from protobuf field <code>uint32 mark = 1;</code>
     * @return int
     */
    public function getMark()
    {
        return $this->mark;
    }

    /**
     * Mark of the connection. If non-zero, the value will be set to SO_MARK.
     *
     * Generated from protobuf field <code>uint32 mark = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMark($var)
    {
        GPBUtil::checkUint32($var);
        $this->mark = $var;

        return $this;
    }

    /**
     * TFO is the state of TFO settings.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     * @return int
     */
    public function getTfo()
    {
        return $this->tfo;
    }

    /**
     * TFO is the state of TFO settings.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TCPFastOpenState tfo = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTfo($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Transport\Internet\SocketConfig\TCPFastOpenState::class);
        $this->tfo = $var;

        return $this;
    }

    /**
     * TProxy is for enabling TProxy socket option.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     * @return int
     */
    public function getTproxy()
    {
        return $this->tproxy;
    }

    /**
     * TProxy is for enabling TProxy socket option.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig.TProxyMode tproxy = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setTproxy($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Transport\Internet\SocketConfig\TProxyMode::class);
        $this->tproxy = $var;

        return $this;
    }

    /**
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     *
     * Generated from protobuf field <code>bool receive_original_dest_address = 4;</code>
     * @return bool
     */
    public function getReceiveOriginalDestAddress()
    {
        return $this->receive_original_dest_address;
    }

    /**
     * ReceiveOriginalDestAddress is for enabling IP_RECVORIGDSTADDR socket
     * option. This option is for UDP only.
     *
     * Generated from protobuf field <code>bool receive_original_dest_address = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setReceiveOriginalDestAddress($var)
    {
        GPBUtil::checkBool($var);
        $this->receive_original_dest_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes bind_address = 5;</code>
     * @return string
     */
    public function getBindAddress()
    {
        return $this->bind_address;
    }

    /**
     * Generated from protobuf field <code>bytes bind_address = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setBindAddress($var)
    {
        GPBUtil::checkString($var, False);
        $this->bind_address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 bind_port = 6;</code>
     * @return int
     */
    public function getBindPort()
    {
        return $this->bind_port;
    }

    /**
     * Generated from protobuf field <code>uint32 bind_port = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setBindPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->bind_port = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 7;</code>
     * @return bool
     */
    public function getAcceptProxyProtocol()
    {
        return $this->accept_proxy_protocol;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptProxyProtocol($var)
    {
        GPBUtil::checkBool($var);
        $this->accept_proxy_protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_interval = 8;</code>
     * @return int
     */
    public function getTcpKeepAliveInterval()
    {
        return $this->tcp_keep_alive_interval;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_interval = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setTcpKeepAliveInterval($var)
    {
        GPBUtil::checkInt32($var);
        $this->tcp_keep_alive_interval = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 tfo_queue_length = 9;</code>
     * @return int
     */
    public function getTfoQueueLength()
    {
        return $this->tfo_queue_length;
    }

    /**
     * Generated from protobuf field <code>uint32 tfo_queue_length = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setTfoQueueLength($var)
    {
        GPBUtil::checkUint32($var);
        $this->tfo_queue_length = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_idle = 10;</code>
     * @return int
     */
    public function getTcpKeepAliveIdle()
    {
        return $this->tcp_keep_alive_idle;
    }

    /**
     * Generated from protobuf field <code>int32 tcp_keep_alive_idle = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setTcpKeepAliveIdle($var)
    {
        GPBUtil::checkInt32($var);
        $this->tcp_keep_alive_idle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string bind_to_device = 11;</code>
     * @return string
     */
    public function getBindToDevice()
    {
        return $this->bind_to_device;
    }

    /**
     * Generated from protobuf field <code>string bind_to_device = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setBindToDevice($var)
    {
        GPBUtil::checkString($var, True);
        $this->bind_to_device = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 rx_buf_size = 12;</code>
     * @return int|string
     */
    public function getRxBufSize()
    {
        return $this->rx_buf_size;
    }

    /**
     * Generated from protobuf field <code>int64 rx_buf_size = 12;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRxBufSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->rx_buf_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 tx_buf_size = 13;</code>
     * @return int|string
     */
    public function getTxBufSize()
    {
        return $this->tx_buf_size;
    }

    /**
     * Generated from protobuf field <code>int64 tx_buf_size = 13;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTxBufSize($var)
    {
        GPBUtil::checkInt64($var);
        $this->tx_buf_size = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool force_buf_size = 14;</code>
     * @return bool
     */
    public function getForceBufSize()
    {
        return $this->force_buf_size;
    }

    /**
     * Generated from protobuf field <code>bool force_buf_size = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setForceBufSize($var)
    {
        GPBUtil::checkBool($var);
        $this->force_buf_size = $var;

        return $this;
    }

}

