<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/config.proto

namespace V2ray\Core\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.StreamConfig</code>
 */
class StreamConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Effective network. Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $protocol = 0;
    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     */
    protected $protocol_name = '';
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.TransportConfig transport_settings = 2;</code>
     */
    private $transport_settings;
    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     */
    protected $security_type = '';
    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any security_settings = 4;</code>
     */
    private $security_settings;
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 6;</code>
     */
    protected $socket_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol
     *           Effective network. Deprecated. Use the string form below.
     *     @type string $protocol_name
     *           Effective network.
     *     @type array<\V2ray\Core\Transport\Internet\TransportConfig>|\Google\Protobuf\Internal\RepeatedField $transport_settings
     *     @type string $security_type
     *           Type of security. Must be a message name of the settings proto.
     *     @type array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $security_settings
     *           Settings for transport security. For now the only choice is TLS.
     *     @type \V2ray\Core\Transport\Internet\SocketConfig $socket_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Effective network. Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getProtocol()
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        return $this->protocol;
    }

    /**
     * Effective network. Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setProtocol($var)
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \V2ray\Core\Transport\Internet\TransportProtocol::class);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @return string
     */
    public function getProtocolName()
    {
        return $this->protocol_name;
    }

    /**
     * Effective network.
     *
     * Generated from protobuf field <code>string protocol_name = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.TransportConfig transport_settings = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTransportSettings()
    {
        return $this->transport_settings;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.TransportConfig transport_settings = 2;</code>
     * @param array<\V2ray\Core\Transport\Internet\TransportConfig>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTransportSettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Transport\Internet\TransportConfig::class);
        $this->transport_settings = $arr;

        return $this;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @return string
     */
    public function getSecurityType()
    {
        return $this->security_type;
    }

    /**
     * Type of security. Must be a message name of the settings proto.
     *
     * Generated from protobuf field <code>string security_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setSecurityType($var)
    {
        GPBUtil::checkString($var, True);
        $this->security_type = $var;

        return $this;
    }

    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any security_settings = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSecuritySettings()
    {
        return $this->security_settings;
    }

    /**
     * Settings for transport security. For now the only choice is TLS.
     *
     * Generated from protobuf field <code>repeated .google.protobuf.Any security_settings = 4;</code>
     * @param array<\Google\Protobuf\Any>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSecuritySettings($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->security_settings = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 6;</code>
     * @return \V2ray\Core\Transport\Internet\SocketConfig|null
     */
    public function getSocketSettings()
    {
        return $this->socket_settings;
    }

    public function hasSocketSettings()
    {
        return isset($this->socket_settings);
    }

    public function clearSocketSettings()
    {
        unset($this->socket_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 6;</code>
     * @param \V2ray\Core\Transport\Internet\SocketConfig $var
     * @return $this
     */
    public function setSocketSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Transport\Internet\SocketConfig::class);
        $this->socket_settings = $var;

        return $this;
    }

}

