<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/config.proto

namespace V2ray\Core\Transport\Internet;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.TransportConfig</code>
 */
class TransportConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $protocol = 0;
    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     */
    protected $protocol_name = '';
    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.google.protobuf.Any settings = 2;</code>
     */
    protected $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $protocol
     *           Type of network that this settings supports.
     *           Deprecated. Use the string form below.
     *     @type string $protocol_name
     *           Type of network that this settings supports.
     *     @type \Google\Protobuf\Any $settings
     *           Specific settings. Must be of the transports.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getProtocol()
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        return $this->protocol;
    }

    /**
     * Type of network that this settings supports.
     * Deprecated. Use the string form below.
     *
     * Generated from protobuf field <code>.v2ray.core.transport.internet.TransportProtocol protocol = 1 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setProtocol($var)
    {
        @trigger_error('protocol is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkEnum($var, \V2ray\Core\Transport\Internet\TransportProtocol::class);
        $this->protocol = $var;

        return $this;
    }

    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     * @return string
     */
    public function getProtocolName()
    {
        return $this->protocol_name;
    }

    /**
     * Type of network that this settings supports.
     *
     * Generated from protobuf field <code>string protocol_name = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProtocolName($var)
    {
        GPBUtil::checkString($var, True);
        $this->protocol_name = $var;

        return $this;
    }

    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.google.protobuf.Any settings = 2;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getSettings()
    {
        return $this->settings;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Specific settings. Must be of the transports.
     *
     * Generated from protobuf field <code>.google.protobuf.Any settings = 2;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->settings = $var;

        return $this;
    }

}

