<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/request/assembly/config.proto

namespace V2ray\Core\Transport\Internet\Request\Assembly;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.request.assembly.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.google.protobuf.Any assembler = 1;</code>
     */
    protected $assembler = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Any roundtripper = 2;</code>
     */
    protected $roundtripper = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Google\Protobuf\Any $assembler
     *     @type \Google\Protobuf\Any $roundtripper
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Request\Assembly\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any assembler = 1;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getAssembler()
    {
        return $this->assembler;
    }

    public function hasAssembler()
    {
        return isset($this->assembler);
    }

    public function clearAssembler()
    {
        unset($this->assembler);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any assembler = 1;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setAssembler($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->assembler = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any roundtripper = 2;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getRoundtripper()
    {
        return $this->roundtripper;
    }

    public function hasRoundtripper()
    {
        return isset($this->roundtripper);
    }

    public function clearRoundtripper()
    {
        unset($this->roundtripper);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any roundtripper = 2;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setRoundtripper($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->roundtripper = $var;

        return $this;
    }

}

