<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/headers/utp/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Utp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9A\x02\x0A+transport/internet/headers/utp/config.proto\x12)v2ray.core.transport.internet.headers.utp\"\x19\x0A\x06Config\x12\x0F\x0A\x07version\x18\x01 \x01(\x0DB\x9C\x01\x0A-com.v2ray.core.transport.internet.headers.utpP\x01Z=github.com/v2fly/v2ray-core/v5/transport/internet/headers/utp\xAA\x02)V2Ray.Core.Transport.Internet.Headers.Utpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

