<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/dns/fakedns/fakedns.proto

namespace V2ray\Core\App\Dns\Fakedns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.dns.fakedns.FakeDnsPoolMulti</code>
 */
class FakeDnsPoolMulti extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
     */
    private $pools;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\App\Dns\Fakedns\FakeDnsPool>|\Google\Protobuf\Internal\RepeatedField $pools
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Dns\Fakedns\Fakedns::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getPools()
    {
        return $this->pools;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.dns.fakedns.FakeDnsPool pools = 1;</code>
     * @param array<\V2ray\Core\App\Dns\Fakedns\FakeDnsPool>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setPools($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Dns\Fakedns\FakeDnsPool::class);
        $this->pools = $arr;

        return $this;
    }

}

