<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/tcp/config.proto

namespace GPBMetadata\Transport\Internet\Tcp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF1\x02\x0A#transport/internet/tcp/config.proto\x12!v2ray.core.transport.internet.tcp\x1A common/protoext/extensions.proto\"v\x0A\x06Config\x12-\x0A\x0Fheader_settings\x18\x02 \x01(\x0B2\x14.google.protobuf.Any\x12\x1D\x0A\x15accept_proxy_protocol\x18\x03 \x01(\x08:\x18\x82\xB5\x18\x14\x0A\x09transport\x12\x03tcp\x90\xFF)\x01J\x04\x08\x01\x10\x02B\x84\x01\x0A%com.v2ray.core.transport.internet.tcpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/tcp\xAA\x02!V2Ray.Core.Transport.Internet.Tcpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

