<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/udp/config.proto

namespace GPBMetadata\Transport\Internet\Udp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xE1\x01\x0A#transport/internet/udp/config.proto\x12!v2ray.core.transport.internet.udp\"\x08\x0A\x06ConfigB\x84\x01\x0A%com.v2ray.core.transport.internet.udpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/udp\xAA\x02!V2Ray.Core.Transport.Internet.Udpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

