<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/multiobservatory/config.proto

namespace GPBMetadata\App\Observatory\Multiobservatory;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Taggedfeatures\Skeleton::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x91\x03\x0A-app/observatory/multiobservatory/config.proto\x12+v2ray.core.app.observatory.multiobservatory\x1A common/protoext/extensions.proto\"d\x0A\x06Config\x129\x0A\x07holders\x18\x01 \x01(\x0B2(.v2ray.core.common.taggedfeatures.Config:\x1F\x82\xB5\x18\x1B\x0A\x07service\x12\x10multiobservatoryB\xA2\x01\x0A/com.v2ray.core.app.observatory.multiObservatoryP\x01Z?github.com/v2fly/v2ray-core/v5/app/observatory/multiobservatory\xAA\x02+V2Ray.Core.App.Observatory.MultiObservatoryb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

