<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/command/command.proto

namespace V2ray\Core\App\Router\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.router.command.BalancerMsg</code>
 */
class BalancerMsg extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.OverrideInfo override = 5;</code>
     */
    protected $override = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     */
    protected $principle_target = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\App\Router\Command\OverrideInfo $override
     *     @type \V2ray\Core\App\Router\Command\PrincipleTargetInfo $principle_target
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.OverrideInfo override = 5;</code>
     * @return \V2ray\Core\App\Router\Command\OverrideInfo|null
     */
    public function getOverride()
    {
        return $this->override;
    }

    public function hasOverride()
    {
        return isset($this->override);
    }

    public function clearOverride()
    {
        unset($this->override);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.OverrideInfo override = 5;</code>
     * @param \V2ray\Core\App\Router\Command\OverrideInfo $var
     * @return $this
     */
    public function setOverride($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Router\Command\OverrideInfo::class);
        $this->override = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     * @return \V2ray\Core\App\Router\Command\PrincipleTargetInfo|null
     */
    public function getPrincipleTarget()
    {
        return $this->principle_target;
    }

    public function hasPrincipleTarget()
    {
        return isset($this->principle_target);
    }

    public function clearPrincipleTarget()
    {
        unset($this->principle_target);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.router.command.PrincipleTargetInfo principle_target = 6;</code>
     * @param \V2ray\Core\App\Router\Command\PrincipleTargetInfo $var
     * @return $this
     */
    public function setPrincipleTarget($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Router\Command\PrincipleTargetInfo::class);
        $this->principle_target = $var;

        return $this;
    }

}

