<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/shadowsocks2022/config.proto

namespace GPBMetadata\Proxy\Shadowsocks2022;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Address::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x97\x03\x0A\"proxy/shadowsocks2022/config.proto\x12 v2ray.core.proxy.shadowsocks2022\x1A common/protoext/extensions.proto\"\xA0\x01\x0A\x0CClientConfig\x12\x0E\x0A\x06method\x18\x01 \x01(\x09\x12\x0B\x0A\x03psk\x18\x02 \x01(\x0C\x12\x0C\x0A\x04ipsk\x18\x04 \x03(\x0C\x122\x0A\x07address\x18\x05 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x06 \x01(\x0D:#\x82\xB5\x18\x1F\x0A\x08outbound\x12\x0Fshadowsocks2022\x90\xFF)\x01B\x81\x01\x0A\$com.v2ray.core.proxy.shadowsocks2022P\x01Z4github.com/v2fly/v2ray-core/v5/proxy/shadowsocks2022\xAA\x02 V2Ray.Core.Proxy.Shadowsocks2022b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

