<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/address.proto

namespace GPBMetadata\Common\Net;

class Address
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x01\x0A\x18common/net/address.proto\x12\x15v2ray.core.common.net\"7\x0A\x0AIPOrDomain\x12\x0C\x0A\x02ip\x18\x01 \x01(\x0CH\x00\x12\x10\x0A\x06domain\x18\x02 \x01(\x09H\x00B\x09\x0A\x07addressB`\x0A\x19com.v2ray.core.common.netP\x01Z)github.com/v2fly/v2ray-core/v5/common/net\xAA\x02\x15V2Ray.Core.Common.Netb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

