<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/destination.proto

namespace GPBMetadata\Common\Net;

class Destination
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Network::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB8\x02\x0A\x1Ccommon/net/destination.proto\x12\x15v2ray.core.common.net\x1A\x18common/net/address.proto\"}\x0A\x08Endpoint\x12/\x0A\x07network\x18\x01 \x01(\x0E2\x1E.v2ray.core.common.net.Network\x122\x0A\x07address\x18\x02 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x03 \x01(\x0DB`\x0A\x19com.v2ray.core.common.netP\x01Z)github.com/v2fly/v2ray-core/v5/common/net\xAA\x02\x15V2Ray.Core.Common.Netb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

