<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/network.proto

namespace GPBMetadata\Common\Net;

class Network
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9F\x02\x0A\x18common/net/network.proto\x12\x15v2ray.core.common.net\">\x0A\x0BNetworkList\x12/\x0A\x07network\x18\x01 \x03(\x0E2\x1E.v2ray.core.common.net.Network*B\x0A\x07Network\x12\x0B\x0A\x07Unknown\x10\x00\x12\x0E\x0A\x06RawTCP\x10\x01\x1A\x02\x08\x01\x12\x07\x0A\x03TCP\x10\x02\x12\x07\x0A\x03UDP\x10\x03\x12\x08\x0A\x04UNIX\x10\x04B`\x0A\x19com.v2ray.core.common.netP\x01Z)github.com/v2fly/v2ray-core/v5/common/net\xAA\x02\x15V2Ray.Core.Common.Netb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

