<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/kcp/config.proto

namespace GPBMetadata\Transport\Internet\Kcp;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAA\x08\x0A#transport/internet/kcp/config.proto\x12!v2ray.core.transport.internet.kcp\x1A common/protoext/extensions.proto\"\x14\x0A\x03MTU\x12\x0D\x0A\x05value\x18\x01 \x01(\x0D\"\x14\x0A\x03TTI\x12\x0D\x0A\x05value\x18\x01 \x01(\x0D\"\x1F\x0A\x0EUplinkCapacity\x12\x0D\x0A\x05value\x18\x01 \x01(\x0D\"!\x0A\x10DownlinkCapacity\x12\x0D\x0A\x05value\x18\x01 \x01(\x0D\"\x1B\x0A\x0BWriteBuffer\x12\x0C\x0A\x04size\x18\x01 \x01(\x0D\"\x1A\x0A\x0AReadBuffer\x12\x0C\x0A\x04size\x18\x01 \x01(\x0D\"!\x0A\x0FConnectionReuse\x12\x0E\x0A\x06enable\x18\x01 \x01(\x08\"\x1E\x0A\x0EEncryptionSeed\x12\x0C\x0A\x04seed\x18\x01 \x01(\x09\"\xC2\x04\x0A\x06Config\x123\x0A\x03mtu\x18\x01 \x01(\x0B2&.v2ray.core.transport.internet.kcp.MTU\x123\x0A\x03tti\x18\x02 \x01(\x0B2&.v2ray.core.transport.internet.kcp.TTI\x12J\x0A\x0Fuplink_capacity\x18\x03 \x01(\x0B21.v2ray.core.transport.internet.kcp.UplinkCapacity\x12N\x0A\x11downlink_capacity\x18\x04 \x01(\x0B23.v2ray.core.transport.internet.kcp.DownlinkCapacity\x12\x12\x0A\x0Acongestion\x18\x05 \x01(\x08\x12D\x0A\x0Cwrite_buffer\x18\x06 \x01(\x0B2..v2ray.core.transport.internet.kcp.WriteBuffer\x12B\x0A\x0Bread_buffer\x18\x07 \x01(\x0B2-.v2ray.core.transport.internet.kcp.ReadBuffer\x12+\x0A\x0Dheader_config\x18\x08 \x01(\x0B2\x14.google.protobuf.Any\x12?\x0A\x04seed\x18\x0A \x01(\x0B21.v2ray.core.transport.internet.kcp.EncryptionSeed: \x82\xB5\x18\x1C\x0A\x09transport\x12\x03kcp\x8A\xFF)\x04mkcp\x90\xFF)\x01J\x04\x08\x09\x10\x0AB\x84\x01\x0A%com.v2ray.core.transport.internet.kcpP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/kcp\xAA\x02!V2Ray.Core.Transport.Internet.Kcpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

