<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/command/command.proto

namespace GPBMetadata\App\Observatory\Command;

class Command
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\App\Observatory\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD6\x04\x0A%app/observatory/command/command.proto\x12\"v2ray.core.app.observatory.command\x1A\x1Capp/observatory/config.proto\"'\x0A\x18GetOutboundStatusRequest\x12\x0B\x0A\x03Tag\x18\x01 \x01(\x09\"Z\x0A\x19GetOutboundStatusResponse\x12=\x0A\x06status\x18\x01 \x01(\x0B2-.v2ray.core.app.observatory.ObservationResult\"(\x0A\x06Config:\x1E\x82\xB5\x18\x1A\x0A\x0Bgrpcservice\x12\x0Bobservatory2\xA9\x01\x0A\x12ObservatoryService\x12\x92\x01\x0A\x11GetOutboundStatus\x12<.v2ray.core.app.observatory.command.GetOutboundStatusRequest\x1A=.v2ray.core.app.observatory.command.GetOutboundStatusResponse\"\x00B\x87\x01\x0A&com.v2ray.core.app.observatory.commandP\x01Z6github.com/v2fly/v2ray-core/v5/app/observatory/command\xAA\x02\"V2Ray.Core.App.Observatory.Commandb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

