<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/http/simplified/config.proto

namespace GPBMetadata\Proxy\Http\Simplified;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x9A\x03\x0A\"proxy/http/simplified/config.proto\x12 v2ray.core.proxy.http.simplified\x1A\x18common/net/address.proto\"#\x0A\x0CServerConfig:\x13\x82\xB5\x18\x0F\x0A\x07inbound\x12\x04http\"\x86\x01\x0A\x0CClientConfig\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D\x12\x1E\x0A\x16h1_skip_wait_for_reply\x18\x03 \x01(\x08:\x14\x82\xB5\x18\x10\x0A\x08outbound\x12\x04httpB\x81\x01\x0A\$com.v2ray.core.proxy.http.simplifiedP\x01Z4github.com/v2fly/v2ray-core/v5/proxy/http/simplified\xAA\x02 V2Ray.Core.Proxy.Http.Simplifiedb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

