<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/request/stereotype/meek/config.proto

namespace GPBMetadata\Transport\Internet\Request\Stereotype\Meek;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xED\x02\x0A7transport/internet/request/stereotype/meek/config.proto\x125v2ray.core.transport.internet.request.stereotype.meek\"0\x0A\x06Config\x12\x0B\x0A\x03url\x18\x01 \x01(\x09:\x19\x82\xB5\x18\x15\x0A\x09transport\x12\x04meek\x90\xFF)\x01B\xC0\x01\x0A9com.v2ray.core.transport.internet.request.stereotype.meekP\x01ZIgithub.com/v2fly/v2ray-core/v5/transport/internet/request/stereotype/meek\xAA\x025V2Ray.Core.Transport.Internet.Request.Stereotype.Meekb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

