<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/log/command/config.proto

namespace GPBMetadata\App\Log\Command;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA0\x04\x0A\x1Capp/log/command/config.proto\x12\x1Av2ray.core.app.log.command\"\x08\x0A\x06Config\"\x16\x0A\x14RestartLoggerRequest\"\x17\x0A\x15RestartLoggerResponse\"\x12\x0A\x10FollowLogRequest\"\$\x0A\x11FollowLogResponse\x12\x0F\x0A\x07message\x18\x01 \x01(\x092\xF5\x01\x0A\x0DLoggerService\x12v\x0A\x0DRestartLogger\x120.v2ray.core.app.log.command.RestartLoggerRequest\x1A1.v2ray.core.app.log.command.RestartLoggerResponse\"\x00\x12l\x0A\x09FollowLog\x12,.v2ray.core.app.log.command.FollowLogRequest\x1A-.v2ray.core.app.log.command.FollowLogResponse\"\x000\x01Bo\x0A\x1Ecom.v2ray.core.app.log.commandP\x01Z.github.com/v2fly/v2ray-core/v5/app/log/command\xAA\x02\x1AV2Ray.Core.App.Log.Commandb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

