<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/subscription/config.proto

namespace V2ray\Core\App\Subscription;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Config is the settings for Subscription Manager.
 *
 * Generated from protobuf message <code>v2ray.core.app.subscription.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.ImportSource imports = 1;</code>
     */
    private $imports;
    /**
     * Generated from protobuf field <code>bytes nonnative_converter_overlay = 2;</code>
     */
    protected $nonnative_converter_overlay = '';
    /**
     * Generated from protobuf field <code>string nonnative_converter_overlay_file = 96002 [(.v2ray.core.common.protoext.field_opt) = {</code>
     */
    protected $nonnative_converter_overlay_file = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\App\Subscription\ImportSource>|\Google\Protobuf\Internal\RepeatedField $imports
     *     @type string $nonnative_converter_overlay
     *     @type string $nonnative_converter_overlay_file
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Subscription\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.ImportSource imports = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getImports()
    {
        return $this->imports;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.ImportSource imports = 1;</code>
     * @param array<\V2ray\Core\App\Subscription\ImportSource>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setImports($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Subscription\ImportSource::class);
        $this->imports = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes nonnative_converter_overlay = 2;</code>
     * @return string
     */
    public function getNonnativeConverterOverlay()
    {
        return $this->nonnative_converter_overlay;
    }

    /**
     * Generated from protobuf field <code>bytes nonnative_converter_overlay = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNonnativeConverterOverlay($var)
    {
        GPBUtil::checkString($var, False);
        $this->nonnative_converter_overlay = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string nonnative_converter_overlay_file = 96002 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @return string
     */
    public function getNonnativeConverterOverlayFile()
    {
        return $this->nonnative_converter_overlay_file;
    }

    /**
     * Generated from protobuf field <code>string nonnative_converter_overlay_file = 96002 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @param string $var
     * @return $this
     */
    public function setNonnativeConverterOverlayFile($var)
    {
        GPBUtil::checkString($var, True);
        $this->nonnative_converter_overlay_file = $var;

        return $this;
    }

}

