<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vless/encoding/addons.proto

namespace GPBMetadata\Proxy\Vless\Encoding;

class Addons
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF2\x01\x0A!proxy/vless/encoding/addons.proto\x12\x1Fv2ray.core.proxy.vless.encoding\"\$\x0A\x06Addons\x12\x0C\x0A\x04Flow\x18\x01 \x01(\x09\x12\x0C\x0A\x04Seed\x18\x02 \x01(\x0CB~\x0A#com.v2ray.core.proxy.vless.encodingP\x01Z3github.com/v2fly/v2ray-core/v5/proxy/vless/encoding\xAA\x02\x1FV2Ray.Core.Proxy.Vless.Encodingb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

