<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/domainsocket/config.proto

namespace V2ray\Core\Transport\Internet\Domainsocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.domainsocket.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Path of the domain socket. This overrides the IP/Port parameter from
     * upstream caller.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     */
    protected $path = '';
    /**
     * Abstract specifies whether to use abstract namespace or not.
     * Traditionally Unix domain socket is file system based. Abstract domain
     * socket can be used without acquiring file lock.
     *
     * Generated from protobuf field <code>bool abstract = 2;</code>
     */
    protected $abstract = false;
    /**
     * Some apps, eg. haproxy, use the full length of sockaddr_un.sun_path to
     * connect(2) or bind(2) when using abstract UDS.
     *
     * Generated from protobuf field <code>bool padding = 3;</code>
     */
    protected $padding = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           Path of the domain socket. This overrides the IP/Port parameter from
     *           upstream caller.
     *     @type bool $abstract
     *           Abstract specifies whether to use abstract namespace or not.
     *           Traditionally Unix domain socket is file system based. Abstract domain
     *           socket can be used without acquiring file lock.
     *     @type bool $padding
     *           Some apps, eg. haproxy, use the full length of sockaddr_un.sun_path to
     *           connect(2) or bind(2) when using abstract UDS.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Domainsocket\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Path of the domain socket. This overrides the IP/Port parameter from
     * upstream caller.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Path of the domain socket. This overrides the IP/Port parameter from
     * upstream caller.
     *
     * Generated from protobuf field <code>string path = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Abstract specifies whether to use abstract namespace or not.
     * Traditionally Unix domain socket is file system based. Abstract domain
     * socket can be used without acquiring file lock.
     *
     * Generated from protobuf field <code>bool abstract = 2;</code>
     * @return bool
     */
    public function getAbstract()
    {
        return $this->abstract;
    }

    /**
     * Abstract specifies whether to use abstract namespace or not.
     * Traditionally Unix domain socket is file system based. Abstract domain
     * socket can be used without acquiring file lock.
     *
     * Generated from protobuf field <code>bool abstract = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setAbstract($var)
    {
        GPBUtil::checkBool($var);
        $this->abstract = $var;

        return $this;
    }

    /**
     * Some apps, eg. haproxy, use the full length of sockaddr_un.sun_path to
     * connect(2) or bind(2) when using abstract UDS.
     *
     * Generated from protobuf field <code>bool padding = 3;</code>
     * @return bool
     */
    public function getPadding()
    {
        return $this->padding;
    }

    /**
     * Some apps, eg. haproxy, use the full length of sockaddr_un.sun_path to
     * connect(2) or bind(2) when using abstract UDS.
     *
     * Generated from protobuf field <code>bool padding = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setPadding($var)
    {
        GPBUtil::checkBool($var);
        $this->padding = $var;

        return $this;
    }

}

