<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/socks/simplified/config.proto

namespace GPBMetadata\Proxy\Socks\Simplified;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        \GPBMetadata\Common\Net\Packetaddr\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB2\x04\x0A#proxy/socks/simplified/config.proto\x12!v2ray.core.proxy.socks.simplified\x1A\x18common/net/address.proto\x1A\"common/net/packetaddr/config.proto\"\xB1\x01\x0A\x0CServerConfig\x122\x0A\x07address\x18\x03 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x13\x0A\x0Budp_enabled\x18\x04 \x01(\x08\x12B\x0A\x0Fpacket_encoding\x18\x07 \x01(\x0E2).v2ray.core.net.packetaddr.PacketAddrType:\x14\x82\xB5\x18\x10\x0A\x07inbound\x12\x05socks\"g\x0A\x0CClientConfig\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D:\x15\x82\xB5\x18\x11\x0A\x08outbound\x12\x05socksB\x84\x01\x0A%com.v2ray.core.proxy.socks.simplifiedP\x01Z5github.com/v2fly/v2ray-core/v5/proxy/socks/simplified\xAA\x02!V2Ray.Core.Proxy.Socks.Simplifiedb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

