<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/request/assembler/simple/config.proto

namespace GPBMetadata\Transport\Internet\Request\Assembler\Simple;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB8\x05\x0A8transport/internet/request/assembler/simple/config.proto\x126v2ray.core.transport.internet.request.assembler.simple\"\x9B\x02\x0A\x0CClientConfig\x12\x16\x0A\x0Emax_write_size\x18\x01 \x01(\x05\x12 \x0A\x18wait_subsequent_write_ms\x18\x02 \x01(\x05\x12#\x0A\x1Binitial_polling_interval_ms\x18\x03 \x01(\x05\x12\x1F\x0A\x17max_polling_interval_ms\x18\x04 \x01(\x05\x12\x1F\x0A\x17min_polling_interval_ms\x18\x05 \x01(\x05\x12\x16\x0A\x0Ebackoff_factor\x18\x06 \x01(\x02\x12 \x0A\x18failed_retry_interval_ms\x18\x07 \x01(\x05:0\x82\xB5\x18,\x0A\"transport.request.assembler.client\x12\x06simple\"X\x0A\x0CServerConfig\x12\x16\x0A\x0Emax_write_size\x18\x01 \x01(\x05:0\x82\xB5\x18,\x0A\"transport.request.assembler.server\x12\x06simpleB\xC3\x01\x0A:com.v2ray.core.transport.internet.request.assembler.simpleP\x01ZJgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembler/simple\xAA\x026V2Ray.Core.Transport.Internet.Request.Assembler.Simpleb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

