<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: config.proto

namespace GPBMetadata;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Transport\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA4\x05\x0A\x0Cconfig.proto\x12\x0Av2ray.core\x1A\x16transport/config.proto\"\xF7\x01\x0A\x06Config\x121\x0A\x07inbound\x18\x01 \x03(\x0B2 .v2ray.core.InboundHandlerConfig\x123\x0A\x08outbound\x18\x02 \x03(\x0B2!.v2ray.core.OutboundHandlerConfig\x12!\x0A\x03app\x18\x04 \x03(\x0B2\x14.google.protobuf.Any\x123\x0A\x09transport\x18\x05 \x01(\x0B2\x1C.v2ray.core.transport.ConfigB\x02\x18\x01\x12'\x0A\x09extension\x18\x06 \x03(\x0B2\x14.google.protobuf.AnyJ\x04\x08\x03\x10\x04\"\x82\x01\x0A\x14InboundHandlerConfig\x12\x0B\x0A\x03tag\x18\x01 \x01(\x09\x12/\x0A\x11receiver_settings\x18\x02 \x01(\x0B2\x14.google.protobuf.Any\x12,\x0A\x0Eproxy_settings\x18\x03 \x01(\x0B2\x14.google.protobuf.Any\"\xA2\x01\x0A\x15OutboundHandlerConfig\x12\x0B\x0A\x03tag\x18\x01 \x01(\x09\x12-\x0A\x0Fsender_settings\x18\x02 \x01(\x0B2\x14.google.protobuf.Any\x12,\x0A\x0Eproxy_settings\x18\x03 \x01(\x0B2\x14.google.protobuf.Any\x12\x0E\x0A\x06expire\x18\x04 \x01(\x03\x12\x0F\x0A\x07comment\x18\x05 \x01(\x09BD\x0A\x0Ecom.v2ray.coreP\x01Z#github.com/v2fly/v2ray-core/v5;core\xAA\x02\x0AV2Ray.Coreb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

