<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/domainsocket/config.proto

namespace GPBMetadata\Transport\Internet\Domainsocket;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDE\x02\x0A,transport/internet/domainsocket/config.proto\x12*v2ray.core.transport.internet.domainsocket\"X\x0A\x06Config\x12\x0C\x0A\x04path\x18\x01 \x01(\x09\x12\x10\x0A\x08abstract\x18\x02 \x01(\x08\x12\x0F\x0A\x07padding\x18\x03 \x01(\x08:\x1D\x82\xB5\x18\x19\x0A\x09transport\x12\x0CdomainsocketB\x9F\x01\x0A.com.v2ray.core.transport.internet.domainsocketP\x01Z>github.com/v2fly/v2ray-core/v5/transport/internet/domainsocket\xAA\x02*V2Ray.Core.Transport.Internet.DomainSocketb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

