<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/trojan/simplified/config.proto

namespace GPBMetadata\Proxy\Trojan\Simplified;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        \GPBMetadata\Common\Net\Packetaddr\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x90\x04\x0A\$proxy/trojan/simplified/config.proto\x12\"v2ray.core.proxy.trojan.simplified\x1A\x18common/net/address.proto\x1A\"common/net/packetaddr/config.proto\"x\x0A\x0CServerConfig\x12\x0D\x0A\x05users\x18\x01 \x03(\x09\x12B\x0A\x0Fpacket_encoding\x18\x02 \x01(\x0E2).v2ray.core.net.packetaddr.PacketAddrType:\x15\x82\xB5\x18\x11\x0A\x07inbound\x12\x06trojan\"z\x0A\x0CClientConfig\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D\x12\x10\x0A\x08password\x18\x03 \x01(\x09:\x16\x82\xB5\x18\x12\x0A\x08outbound\x12\x06trojanB\x87\x01\x0A&com.v2ray.core.proxy.trojan.simplifiedP\x01Z6github.com/v2fly/v2ray-core/v5/proxy/trojan/simplified\xAA\x02\"V2Ray.Core.Proxy.Trojan.Simplifiedb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

