<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/tls/config.proto

namespace GPBMetadata\Transport\Internet\Tls;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA6\x08\x0A#transport/internet/tls/config.proto\x12!v2ray.core.transport.internet.tls\"\xA5\x02\x0A\x0BCertificate\x12\x13\x0A\x0BCertificate\x18\x01 \x01(\x0C\x12\x0B\x0A\x03Key\x18\x02 \x01(\x0C\x12C\x0A\x05usage\x18\x03 \x01(\x0E24.v2ray.core.transport.internet.tls.Certificate.Usage\x12-\x0A\x10certificate_file\x18\x81\xEE\x05 \x01(\x09B\x11\x82\xB5\x18\x0D\"\x0BCertificate\x12\x1D\x0A\x08key_file\x18\x82\xEE\x05 \x01(\x09B\x09\x82\xB5\x18\x05\"\x03Key\"a\x0A\x05Usage\x12\x10\x0A\x0CENCIPHERMENT\x10\x00\x12\x14\x0A\x10AUTHORITY_VERIFY\x10\x01\x12\x13\x0A\x0FAUTHORITY_ISSUE\x10\x02\x12\x1B\x0A\x17AUTHORITY_VERIFY_CLIENT\x10\x03\"\xA4\x04\x0A\x06Config\x12\x1E\x0A\x0Eallow_insecure\x18\x01 \x01(\x08B\x06\x82\xB5\x18\x02(\x01\x12C\x0A\x0Bcertificate\x18\x02 \x03(\x0B2..v2ray.core.transport.internet.tls.Certificate\x12\x13\x0A\x0Bserver_name\x18\x03 \x01(\x09\x12\x15\x0A\x0Dnext_protocol\x18\x04 \x03(\x09\x12!\x0A\x19enable_session_resumption\x18\x05 \x01(\x08\x12\x1B\x0A\x13disable_system_root\x18\x06 \x01(\x08\x12,\x0A\$pinned_peer_certificate_chain_sha256\x18\x07 \x03(\x0C\x12!\x0A\x19verify_client_certificate\x18\x08 \x01(\x08\x12I\x0A\x0Bmin_version\x18\x09 \x01(\x0E24.v2ray.core.transport.internet.tls.Config.TLSVersion\x12I\x0A\x0Bmax_version\x18\x0A \x01(\x0E24.v2ray.core.transport.internet.tls.Config.TLSVersion\"I\x0A\x0ATLSVersion\x12\x0B\x0A\x07Default\x10\x00\x12\x0A\x0A\x06TLS1_0\x10\x01\x12\x0A\x0A\x06TLS1_1\x10\x02\x12\x0A\x0A\x06TLS1_2\x10\x03\x12\x0A\x0A\x06TLS1_3\x10\x04:\x17\x82\xB5\x18\x13\x0A\x08security\x12\x03tls\x90\xFF)\x01B\x84\x01\x0A%com.v2ray.core.transport.internet.tlsP\x01Z5github.com/v2fly/v2ray-core/v5/transport/internet/tls\xAA\x02!V2Ray.Core.Transport.Internet.Tlsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

