<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/config.proto

namespace GPBMetadata\Transport;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Transport\Internet\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEF\x01\x0A\x16transport/config.proto\x12\x14v2ray.core.transport\"X\x0A\x06Config\x12J\x0A\x12transport_settings\x18\x01 \x03(\x0B2..v2ray.core.transport.internet.TransportConfig:\x02\x18\x01B]\x0A\x18com.v2ray.core.transportP\x01Z(github.com/v2fly/v2ray-core/v5/transport\xAA\x02\x14V2Ray.Core.Transportb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

