<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/tls/config.proto

namespace V2ray\Core\Transport\Internet\Tls\Config;

use UnexpectedValueException;

/**
 * Protobuf type <code>v2ray.core.transport.internet.tls.Config.TLSVersion</code>
 */
class TLSVersion
{
    /**
     * Generated from protobuf enum <code>Default = 0;</code>
     */
    const PBDefault = 0;
    /**
     * Generated from protobuf enum <code>TLS1_0 = 1;</code>
     */
    const TLS1_0 = 1;
    /**
     * Generated from protobuf enum <code>TLS1_1 = 2;</code>
     */
    const TLS1_1 = 2;
    /**
     * Generated from protobuf enum <code>TLS1_2 = 3;</code>
     */
    const TLS1_2 = 3;
    /**
     * Generated from protobuf enum <code>TLS1_3 = 4;</code>
     */
    const TLS1_3 = 4;

    private static $valueToName = [
        self::PBDefault => 'Default',
        self::TLS1_0 => 'TLS1_0',
        self::TLS1_1 => 'TLS1_1',
        self::TLS1_2 => 'TLS1_2',
        self::TLS1_3 => 'TLS1_3',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            $pbconst =  __CLASS__. '::PB' . strtoupper($name);
            if (!defined($pbconst)) {
                throw new UnexpectedValueException(sprintf(
                        'Enum %s has no value defined for name %s', __CLASS__, $name));
            }
            return constant($pbconst);
        }
        return constant($const);
    }
}

