<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/protoext/testing/test.proto

namespace V2ray\Core\Common\Protoext\Testing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.common.protoext.testing.TestingMessage</code>
 */
class TestingMessage extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string test_field = 1 [(.v2ray.core.common.protoext.field_opt) = {</code>
     */
    protected $test_field = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $test_field
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Protoext\Testing\Test::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string test_field = 1 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @return string
     */
    public function getTestField()
    {
        return $this->test_field;
    }

    /**
     * Generated from protobuf field <code>string test_field = 1 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @param string $var
     * @return $this
     */
    public function setTestField($var)
    {
        GPBUtil::checkString($var, True);
        $this->test_field = $var;

        return $this;
    }

}

