<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/shadowsocks2022/config.proto

namespace V2ray\Core\Proxy\Shadowsocks2022;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.shadowsocks2022.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string method = 1;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>bytes psk = 2;</code>
     */
    protected $psk = '';
    /**
     * Generated from protobuf field <code>repeated bytes ipsk = 4;</code>
     */
    private $ipsk;
    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 5;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>uint32 port = 6;</code>
     */
    protected $port = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $method
     *     @type string $psk
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $ipsk
     *     @type \V2ray\Core\Common\Net\IPOrDomain $address
     *     @type int $port
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Shadowsocks2022\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string method = 1;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes psk = 2;</code>
     * @return string
     */
    public function getPsk()
    {
        return $this->psk;
    }

    /**
     * Generated from protobuf field <code>bytes psk = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPsk($var)
    {
        GPBUtil::checkString($var, False);
        $this->psk = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ipsk = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIpsk()
    {
        return $this->ipsk;
    }

    /**
     * Generated from protobuf field <code>repeated bytes ipsk = 4;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIpsk($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::BYTES);
        $this->ipsk = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 5;</code>
     * @return \V2ray\Core\Common\Net\IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 5;</code>
     * @param \V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 6;</code>
     * @return int
     */
    public function getPort()
    {
        return $this->port;
    }

    /**
     * Generated from protobuf field <code>uint32 port = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setPort($var)
    {
        GPBUtil::checkUint32($var);
        $this->port = $var;

        return $this;
    }

}

