<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/socks/simplified/config.proto

namespace V2ray\Core\Proxy\Socks\Simplified;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.socks.simplified.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     */
    protected $udp_enabled = false;
    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     */
    protected $packet_encoding = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Common\Net\IPOrDomain $address
     *     @type bool $udp_enabled
     *     @type int $packet_encoding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Socks\Simplified\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @return \V2ray\Core\Common\Net\IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @param \V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @return bool
     */
    public function getUdpEnabled()
    {
        return $this->udp_enabled;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUdpEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->udp_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     * @return int
     */
    public function getPacketEncoding()
    {
        return $this->packet_encoding;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPacketEncoding($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Net\Packetaddr\PacketAddrType::class);
        $this->packet_encoding = $var;

        return $this;
    }

}

