<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/multiobservatory/config.proto

namespace V2ray\Core\App\Observatory\Multiobservatory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.observatory.multiobservatory.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.common.taggedfeatures.Config holders = 1;</code>
     */
    protected $holders = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Common\Taggedfeatures\Config $holders
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Observatory\Multiobservatory\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.taggedfeatures.Config holders = 1;</code>
     * @return \V2ray\Core\Common\Taggedfeatures\Config|null
     */
    public function getHolders()
    {
        return $this->holders;
    }

    public function hasHolders()
    {
        return isset($this->holders);
    }

    public function clearHolders()
    {
        unset($this->holders);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.taggedfeatures.Config holders = 1;</code>
     * @param \V2ray\Core\Common\Taggedfeatures\Config $var
     * @return $this
     */
    public function setHolders($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Taggedfeatures\Config::class);
        $this->holders = $var;

        return $this;
    }

}

