<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/tls/utls/config.proto

namespace V2ray\Core\Transport\Internet\Tls\Utls;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.tls.utls.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.Config tls_config = 1;</code>
     */
    protected $tls_config = null;
    /**
     * Generated from protobuf field <code>string imitate = 2;</code>
     */
    protected $imitate = '';
    /**
     * Generated from protobuf field <code>bool noSNI = 3;</code>
     */
    protected $noSNI = false;
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.utls.ForcedALPN force_alpn = 4;</code>
     */
    protected $force_alpn = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Transport\Internet\Tls\Config $tls_config
     *     @type string $imitate
     *     @type bool $noSNI
     *     @type int $force_alpn
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Tls\Utls\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.Config tls_config = 1;</code>
     * @return \V2ray\Core\Transport\Internet\Tls\Config|null
     */
    public function getTlsConfig()
    {
        return $this->tls_config;
    }

    public function hasTlsConfig()
    {
        return isset($this->tls_config);
    }

    public function clearTlsConfig()
    {
        unset($this->tls_config);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.Config tls_config = 1;</code>
     * @param \V2ray\Core\Transport\Internet\Tls\Config $var
     * @return $this
     */
    public function setTlsConfig($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Transport\Internet\Tls\Config::class);
        $this->tls_config = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string imitate = 2;</code>
     * @return string
     */
    public function getImitate()
    {
        return $this->imitate;
    }

    /**
     * Generated from protobuf field <code>string imitate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setImitate($var)
    {
        GPBUtil::checkString($var, True);
        $this->imitate = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool noSNI = 3;</code>
     * @return bool
     */
    public function getNoSNI()
    {
        return $this->noSNI;
    }

    /**
     * Generated from protobuf field <code>bool noSNI = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoSNI($var)
    {
        GPBUtil::checkBool($var);
        $this->noSNI = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.utls.ForcedALPN force_alpn = 4;</code>
     * @return int
     */
    public function getForceAlpn()
    {
        return $this->force_alpn;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.tls.utls.ForcedALPN force_alpn = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setForceAlpn($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Transport\Internet\Tls\Utls\ForcedALPN::class);
        $this->force_alpn = $var;

        return $this;
    }

}

