<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vmess/inbound/config.proto

namespace V2ray\Core\Proxy\Vmess\Inbound;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.vmess.inbound.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.User user = 1;</code>
     */
    private $user;
    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     */
    protected $default = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     */
    protected $detour = null;
    /**
     * Generated from protobuf field <code>bool secure_encryption_only = 4;</code>
     */
    protected $secure_encryption_only = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $user
     *     @type \V2ray\Core\Proxy\Vmess\Inbound\DefaultConfig $default
     *     @type \V2ray\Core\Proxy\Vmess\Inbound\DetourConfig $detour
     *     @type bool $secure_encryption_only
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Vmess\Inbound\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.User user = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUser()
    {
        return $this->user;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.User user = 1;</code>
     * @param array<\V2ray\Core\Common\Protocol\User>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUser($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Common\Protocol\User::class);
        $this->user = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @return \V2ray\Core\Proxy\Vmess\Inbound\DefaultConfig|null
     */
    public function getDefault()
    {
        return $this->default;
    }

    public function hasDefault()
    {
        return isset($this->default);
    }

    public function clearDefault()
    {
        unset($this->default);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DefaultConfig default = 2;</code>
     * @param \V2ray\Core\Proxy\Vmess\Inbound\DefaultConfig $var
     * @return $this
     */
    public function setDefault($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Proxy\Vmess\Inbound\DefaultConfig::class);
        $this->default = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @return \V2ray\Core\Proxy\Vmess\Inbound\DetourConfig|null
     */
    public function getDetour()
    {
        return $this->detour;
    }

    public function hasDetour()
    {
        return isset($this->detour);
    }

    public function clearDetour()
    {
        unset($this->detour);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.vmess.inbound.DetourConfig detour = 3;</code>
     * @param \V2ray\Core\Proxy\Vmess\Inbound\DetourConfig $var
     * @return $this
     */
    public function setDetour($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Proxy\Vmess\Inbound\DetourConfig::class);
        $this->detour = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool secure_encryption_only = 4;</code>
     * @return bool
     */
    public function getSecureEncryptionOnly()
    {
        return $this->secure_encryption_only;
    }

    /**
     * Generated from protobuf field <code>bool secure_encryption_only = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setSecureEncryptionOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->secure_encryption_only = $var;

        return $this;
    }

}

