<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/headers/noop/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Noop;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA2\x02\x0A,transport/internet/headers/noop/config.proto\x12*v2ray.core.transport.internet.headers.noop\"\x08\x0A\x06Config\"\x12\x0A\x10ConnectionConfigB\x9F\x01\x0A.com.v2ray.core.transport.internet.headers.noopP\x01Z>github.com/v2fly/v2ray-core/v5/transport/internet/headers/noop\xAA\x02*V2Ray.Core.Transport.Internet.Headers.Noopb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

