<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/request/assembler/simple/config.proto

namespace V2ray\Core\Transport\Internet\Request\Assembler\Simple;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.request.assembler.simple.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 max_write_size = 1;</code>
     */
    protected $max_write_size = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $max_write_size
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Request\Assembler\Simple\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 max_write_size = 1;</code>
     * @return int
     */
    public function getMaxWriteSize()
    {
        return $this->max_write_size;
    }

    /**
     * Generated from protobuf field <code>int32 max_write_size = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxWriteSize($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_write_size = $var;

        return $this;
    }

}

