<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vless/account.proto

namespace GPBMetadata\Proxy\Vless;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD9\x01\x0A\x19proxy/vless/account.proto\x12\x16v2ray.core.proxy.vless\"7\x0A\x07Account\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x0C\x0A\x04flow\x18\x02 \x01(\x09\x12\x12\x0A\x0Aencryption\x18\x03 \x01(\x09Bc\x0A\x1Acom.v2ray.core.proxy.vlessP\x01Z*github.com/v2fly/v2ray-core/v5/proxy/vless\xAA\x02\x16V2Ray.Core.Proxy.Vlessb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

