<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/socks/config.proto

namespace V2ray\Core\Proxy\Socks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientConfig is the protobuf config for Socks client.
 *
 * Generated from protobuf message <code>v2ray.core.proxy.socks.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Sever is a list of Socks server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    private $server;
    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.Version version = 2;</code>
     */
    protected $version = 0;
    /**
     * Generated from protobuf field <code>bool delay_auth_write = 3;</code>
     */
    protected $delay_auth_write = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $server
     *           Sever is a list of Socks server addresses.
     *     @type int $version
     *     @type bool $delay_auth_write
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Socks\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Sever is a list of Socks server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Sever is a list of Socks server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     * @param array<\V2ray\Core\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Common\Protocol\ServerEndpoint::class);
        $this->server = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.Version version = 2;</code>
     * @return int
     */
    public function getVersion()
    {
        return $this->version;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.Version version = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Proxy\Socks\Version::class);
        $this->version = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool delay_auth_write = 3;</code>
     * @return bool
     */
    public function getDelayAuthWrite()
    {
        return $this->delay_auth_write;
    }

    /**
     * Generated from protobuf field <code>bool delay_auth_write = 3;</code>
     * @param bool $var
     * @return $this
     */
    public function setDelayAuthWrite($var)
    {
        GPBUtil::checkBool($var);
        $this->delay_auth_write = $var;

        return $this;
    }

}

