<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/socks/config.proto

namespace V2ray\Core\Proxy\Socks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ServerConfig is the protobuf config for Socks server.
 *
 * Generated from protobuf message <code>v2ray.core.proxy.socks.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     */
    protected $auth_type = 0;
    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     */
    private $accounts;
    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     */
    protected $address = null;
    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     */
    protected $udp_enabled = false;
    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $timeout = 0;
    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     */
    protected $packet_encoding = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $auth_type
     *     @type array|\Google\Protobuf\Internal\MapField $accounts
     *     @type \V2ray\Core\Common\Net\IPOrDomain $address
     *     @type bool $udp_enabled
     *     @type int $timeout
     *     @type int $user_level
     *     @type int $packet_encoding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Socks\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     * @return int
     */
    public function getAuthType()
    {
        return $this->auth_type;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.proxy.socks.AuthType auth_type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthType($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Proxy\Socks\AuthType::class);
        $this->auth_type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getAccounts()
    {
        return $this->accounts;
    }

    /**
     * Generated from protobuf field <code>map<string, string> accounts = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setAccounts($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->accounts = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @return \V2ray\Core\Common\Net\IPOrDomain|null
     */
    public function getAddress()
    {
        return $this->address;
    }

    public function hasAddress()
    {
        return isset($this->address);
    }

    public function clearAddress()
    {
        unset($this->address);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain address = 3;</code>
     * @param \V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setAddress($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\IPOrDomain::class);
        $this->address = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @return bool
     */
    public function getUdpEnabled()
    {
        return $this->udp_enabled;
    }

    /**
     * Generated from protobuf field <code>bool udp_enabled = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setUdpEnabled($var)
    {
        GPBUtil::checkBool($var);
        $this->udp_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     * @return int
     * @deprecated
     */
    public function getTimeout()
    {
        @trigger_error('timeout is deprecated.', E_USER_DEPRECATED);
        return $this->timeout;
    }

    /**
     * Generated from protobuf field <code>uint32 timeout = 5 [deprecated = true];</code>
     * @param int $var
     * @return $this
     * @deprecated
     */
    public function setTimeout($var)
    {
        @trigger_error('timeout is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkUint32($var);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     * @return int
     */
    public function getPacketEncoding()
    {
        return $this->packet_encoding;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setPacketEncoding($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Net\Packetaddr\PacketAddrType::class);
        $this->packet_encoding = $var;

        return $this;
    }

}

