<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/socks/config.proto

namespace V2ray\Core\Proxy\Socks;

use UnexpectedValueException;

/**
 * Protobuf type <code>v2ray.core.proxy.socks.Version</code>
 */
class Version
{
    /**
     * Generated from protobuf enum <code>SOCKS5 = 0;</code>
     */
    const SOCKS5 = 0;
    /**
     * Generated from protobuf enum <code>SOCKS4 = 1;</code>
     */
    const SOCKS4 = 1;
    /**
     * Generated from protobuf enum <code>SOCKS4A = 2;</code>
     */
    const SOCKS4A = 2;

    private static $valueToName = [
        self::SOCKS5 => 'SOCKS5',
        self::SOCKS4 => 'SOCKS4',
        self::SOCKS4A => 'SOCKS4A',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

