<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/proxyman/config.proto

namespace V2ray\Core\App\Proxyman;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.proxyman.SenderConfig</code>
 */
class SenderConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain via = 1;</code>
     */
    protected $via = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     */
    protected $stream_settings = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     */
    protected $proxy_settings = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     */
    protected $multiplex_settings = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SenderConfig.DomainStrategy domain_strategy = 5;</code>
     */
    protected $domain_strategy = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Common\Net\IPOrDomain $via
     *           Send traffic through the given IP. Only IP is allowed.
     *     @type \V2ray\Core\Transport\Internet\StreamConfig $stream_settings
     *     @type \V2ray\Core\Transport\Internet\ProxyConfig $proxy_settings
     *     @type \V2ray\Core\App\Proxyman\MultiplexingConfig $multiplex_settings
     *     @type int $domain_strategy
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Proxyman\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain via = 1;</code>
     * @return \V2ray\Core\Common\Net\IPOrDomain|null
     */
    public function getVia()
    {
        return $this->via;
    }

    public function hasVia()
    {
        return isset($this->via);
    }

    public function clearVia()
    {
        unset($this->via);
    }

    /**
     * Send traffic through the given IP. Only IP is allowed.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.IPOrDomain via = 1;</code>
     * @param \V2ray\Core\Common\Net\IPOrDomain $var
     * @return $this
     */
    public function setVia($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\IPOrDomain::class);
        $this->via = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     * @return \V2ray\Core\Transport\Internet\StreamConfig|null
     */
    public function getStreamSettings()
    {
        return $this->stream_settings;
    }

    public function hasStreamSettings()
    {
        return isset($this->stream_settings);
    }

    public function clearStreamSettings()
    {
        unset($this->stream_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.StreamConfig stream_settings = 2;</code>
     * @param \V2ray\Core\Transport\Internet\StreamConfig $var
     * @return $this
     */
    public function setStreamSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Transport\Internet\StreamConfig::class);
        $this->stream_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @return \V2ray\Core\Transport\Internet\ProxyConfig|null
     */
    public function getProxySettings()
    {
        return $this->proxy_settings;
    }

    public function hasProxySettings()
    {
        return isset($this->proxy_settings);
    }

    public function clearProxySettings()
    {
        unset($this->proxy_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.ProxyConfig proxy_settings = 3;</code>
     * @param \V2ray\Core\Transport\Internet\ProxyConfig $var
     * @return $this
     */
    public function setProxySettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Transport\Internet\ProxyConfig::class);
        $this->proxy_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @return \V2ray\Core\App\Proxyman\MultiplexingConfig|null
     */
    public function getMultiplexSettings()
    {
        return $this->multiplex_settings;
    }

    public function hasMultiplexSettings()
    {
        return isset($this->multiplex_settings);
    }

    public function clearMultiplexSettings()
    {
        unset($this->multiplex_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.MultiplexingConfig multiplex_settings = 4;</code>
     * @param \V2ray\Core\App\Proxyman\MultiplexingConfig $var
     * @return $this
     */
    public function setMultiplexSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Proxyman\MultiplexingConfig::class);
        $this->multiplex_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SenderConfig.DomainStrategy domain_strategy = 5;</code>
     * @return int
     */
    public function getDomainStrategy()
    {
        return $this->domain_strategy;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SenderConfig.DomainStrategy domain_strategy = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setDomainStrategy($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\App\Proxyman\SenderConfig\DomainStrategy::class);
        $this->domain_strategy = $var;

        return $this;
    }

}

