<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/headers/wireguard/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Wireguard;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB0\x02\x0A1transport/internet/headers/wireguard/config.proto\x12/v2ray.core.transport.internet.headers.wireguard\"\x11\x0A\x0FWireguardConfigB\xAE\x01\x0A3com.v2ray.core.transport.internet.headers.wireguardP\x01ZCgithub.com/v2fly/v2ray-core/v5/transport/internet/headers/wireguard\xAA\x02/V2Ray.Core.Transport.Internet.Headers.Wireguardb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

