<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/websocket/config.proto

namespace V2ray\Core\Transport\Internet\Websocket;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.websocket.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * URL path to the WebSocket service. Empty value means root(/).
     *
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.websocket.Header header = 3;</code>
     */
    private $header;
    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 4;</code>
     */
    protected $accept_proxy_protocol = false;
    /**
     * Generated from protobuf field <code>int32 max_early_data = 5;</code>
     */
    protected $max_early_data = 0;
    /**
     * Generated from protobuf field <code>bool use_browser_forwarding = 6;</code>
     */
    protected $use_browser_forwarding = false;
    /**
     * Generated from protobuf field <code>string early_data_header_name = 7;</code>
     */
    protected $early_data_header_name = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $path
     *           URL path to the WebSocket service. Empty value means root(/).
     *     @type array<\V2ray\Core\Transport\Internet\Websocket\Header>|\Google\Protobuf\Internal\RepeatedField $header
     *     @type bool $accept_proxy_protocol
     *     @type int $max_early_data
     *     @type bool $use_browser_forwarding
     *     @type string $early_data_header_name
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Websocket\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * URL path to the WebSocket service. Empty value means root(/).
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * URL path to the WebSocket service. Empty value means root(/).
     *
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.websocket.Header header = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.websocket.Header header = 3;</code>
     * @param array<\V2ray\Core\Transport\Internet\Websocket\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Transport\Internet\Websocket\Header::class);
        $this->header = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 4;</code>
     * @return bool
     */
    public function getAcceptProxyProtocol()
    {
        return $this->accept_proxy_protocol;
    }

    /**
     * Generated from protobuf field <code>bool accept_proxy_protocol = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setAcceptProxyProtocol($var)
    {
        GPBUtil::checkBool($var);
        $this->accept_proxy_protocol = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 max_early_data = 5;</code>
     * @return int
     */
    public function getMaxEarlyData()
    {
        return $this->max_early_data;
    }

    /**
     * Generated from protobuf field <code>int32 max_early_data = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMaxEarlyData($var)
    {
        GPBUtil::checkInt32($var);
        $this->max_early_data = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool use_browser_forwarding = 6;</code>
     * @return bool
     */
    public function getUseBrowserForwarding()
    {
        return $this->use_browser_forwarding;
    }

    /**
     * Generated from protobuf field <code>bool use_browser_forwarding = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setUseBrowserForwarding($var)
    {
        GPBUtil::checkBool($var);
        $this->use_browser_forwarding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string early_data_header_name = 7;</code>
     * @return string
     */
    public function getEarlyDataHeaderName()
    {
        return $this->early_data_header_name;
    }

    /**
     * Generated from protobuf field <code>string early_data_header_name = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setEarlyDataHeaderName($var)
    {
        GPBUtil::checkString($var, True);
        $this->early_data_header_name = $var;

        return $this;
    }

}

