<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/config.proto

namespace V2ray\Core\App\Observatory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.observatory.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * \@Document The selectors for outbound under observation
     *
     * Generated from protobuf field <code>repeated string subject_selector = 2;</code>
     */
    private $subject_selector;
    /**
     * Generated from protobuf field <code>string probe_url = 3;</code>
     */
    protected $probe_url = '';
    /**
     * Generated from protobuf field <code>int64 probe_interval = 4;</code>
     */
    protected $probe_interval = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $subject_selector
     *           \@Document The selectors for outbound under observation
     *     @type string $probe_url
     *     @type int|string $probe_interval
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Observatory\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * \@Document The selectors for outbound under observation
     *
     * Generated from protobuf field <code>repeated string subject_selector = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubjectSelector()
    {
        return $this->subject_selector;
    }

    /**
     * \@Document The selectors for outbound under observation
     *
     * Generated from protobuf field <code>repeated string subject_selector = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubjectSelector($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->subject_selector = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string probe_url = 3;</code>
     * @return string
     */
    public function getProbeUrl()
    {
        return $this->probe_url;
    }

    /**
     * Generated from protobuf field <code>string probe_url = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setProbeUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->probe_url = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int64 probe_interval = 4;</code>
     * @return int|string
     */
    public function getProbeInterval()
    {
        return $this->probe_interval;
    }

    /**
     * Generated from protobuf field <code>int64 probe_interval = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setProbeInterval($var)
    {
        GPBUtil::checkInt64($var);
        $this->probe_interval = $var;

        return $this;
    }

}

