<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/config.proto

namespace V2ray\Core\App\Observatory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.observatory.Intensity</code>
 */
class Intensity extends \Google\Protobuf\Internal\Message
{
    /**
     * \@Document The time interval for a probe request in ms.
     *\@Type time.ms
     *
     * Generated from protobuf field <code>uint32 probe_interval = 1;</code>
     */
    protected $probe_interval = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $probe_interval
     *           \@Document The time interval for a probe request in ms.
     *          \@Type time.ms
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Observatory\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * \@Document The time interval for a probe request in ms.
     *\@Type time.ms
     *
     * Generated from protobuf field <code>uint32 probe_interval = 1;</code>
     * @return int
     */
    public function getProbeInterval()
    {
        return $this->probe_interval;
    }

    /**
     * \@Document The time interval for a probe request in ms.
     *\@Type time.ms
     *
     * Generated from protobuf field <code>uint32 probe_interval = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setProbeInterval($var)
    {
        GPBUtil::checkUint32($var);
        $this->probe_interval = $var;

        return $this;
    }

}

