<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/config.proto

namespace V2ray\Core\App\Observatory;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.observatory.ProbeResult</code>
 */
class ProbeResult extends \Google\Protobuf\Internal\Message
{
    /**
     * \@Document Whether this outbound is usable
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>bool alive = 1;</code>
     */
    protected $alive = false;
    /**
     * \@Document The time for probe request to finish.
     *\@Type time.ms
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>int64 delay = 2;</code>
     */
    protected $delay = 0;
    /**
     * \@Document The error caused this outbound failed to relay probe request
     *\@Restriction NotMachineReadable
     *
     * Generated from protobuf field <code>string last_error_reason = 3;</code>
     */
    protected $last_error_reason = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $alive
     *           \@Document Whether this outbound is usable
     *          \@Restriction ReadOnlyForUser
     *     @type int|string $delay
     *           \@Document The time for probe request to finish.
     *          \@Type time.ms
     *          \@Restriction ReadOnlyForUser
     *     @type string $last_error_reason
     *           \@Document The error caused this outbound failed to relay probe request
     *          \@Restriction NotMachineReadable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Observatory\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * \@Document Whether this outbound is usable
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @return bool
     */
    public function getAlive()
    {
        return $this->alive;
    }

    /**
     * \@Document Whether this outbound is usable
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>bool alive = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setAlive($var)
    {
        GPBUtil::checkBool($var);
        $this->alive = $var;

        return $this;
    }

    /**
     * \@Document The time for probe request to finish.
     *\@Type time.ms
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>int64 delay = 2;</code>
     * @return int|string
     */
    public function getDelay()
    {
        return $this->delay;
    }

    /**
     * \@Document The time for probe request to finish.
     *\@Type time.ms
     *\@Restriction ReadOnlyForUser
     *
     * Generated from protobuf field <code>int64 delay = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setDelay($var)
    {
        GPBUtil::checkInt64($var);
        $this->delay = $var;

        return $this;
    }

    /**
     * \@Document The error caused this outbound failed to relay probe request
     *\@Restriction NotMachineReadable
     *
     * Generated from protobuf field <code>string last_error_reason = 3;</code>
     * @return string
     */
    public function getLastErrorReason()
    {
        return $this->last_error_reason;
    }

    /**
     * \@Document The error caused this outbound failed to relay probe request
     *\@Restriction NotMachineReadable
     *
     * Generated from protobuf field <code>string last_error_reason = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLastErrorReason($var)
    {
        GPBUtil::checkString($var, True);
        $this->last_error_reason = $var;

        return $this;
    }

}

