<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vlite/inbound/config.proto

namespace GPBMetadata\Proxy\Vlite\Inbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x97\x03\x0A proxy/vlite/inbound/config.proto\x12\x1Ev2ray.core.proxy.vlite.inbound\"\xCD\x01\x0A\x11UDPProtocolConfig\x12\x10\x0A\x08password\x18\x03 \x01(\x09\x12\x17\x0A\x0Fscramble_packet\x18\x04 \x01(\x08\x12\x12\x0A\x0Aenable_fec\x18\x05 \x01(\x08\x12\x1C\x0A\x14enable_stabilization\x18\x06 \x01(\x08\x12\x1C\x0A\x14enable_renegotiation\x18\x07 \x01(\x08\x12&\x0A\x1Ehandshake_masking_padding_size\x18\x08 \x01(\x0D:\x15\x82\xB5\x18\x11\x0A\x07inbound\x12\x06vliteuB{\x0A\"com.v2ray.core.proxy.vlite.inboundP\x01Z2github.com/v2fly/v2ray-core/v5/proxy/vlite/inbound\xAA\x02\x1EV2Ray.Core.Proxy.Vlite.Inboundb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

