<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/shadowsocks/simplified/config.proto

namespace GPBMetadata\Proxy\Shadowsocks\Simplified;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Common\Net\Address::initOnce();
        \GPBMetadata\Common\Net\Network::initOnce();
        \GPBMetadata\Common\Net\Packetaddr\Config::initOnce();
        \GPBMetadata\Proxy\Shadowsocks\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC0\x07\x0A)proxy/shadowsocks/simplified/config.proto\x12'v2ray.core.proxy.shadowsocks.simplified\x1A\x18common/net/address.proto\x1A\x18common/net/network.proto\x1A\"common/net/packetaddr/config.proto\x1A\x1Eproxy/shadowsocks/config.proto\"\x82\x02\x0A\x0CServerConfig\x12J\x0A\x06method\x18\x01 \x01(\x0B2:.v2ray.core.proxy.shadowsocks.simplified.CipherTypeWrapper\x12\x10\x0A\x08password\x18\x02 \x01(\x09\x124\x0A\x08networks\x18\x03 \x01(\x0B2\".v2ray.core.common.net.NetworkList\x12B\x0A\x0Fpacket_encoding\x18\x04 \x01(\x0E2).v2ray.core.net.packetaddr.PacketAddrType:\x1A\x82\xB5\x18\x16\x0A\x07inbound\x12\x0Bshadowsocks\"\xFD\x01\x0A\x0CClientConfig\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D\x12J\x0A\x06method\x18\x03 \x01(\x0B2:.v2ray.core.proxy.shadowsocks.simplified.CipherTypeWrapper\x12\x10\x0A\x08password\x18\x04 \x01(\x09\x12,\x0A\"experiment_reduced_iv_head_entropy\x18\x91\xBF\x05 \x01(\x08:\x1F\x82\xB5\x18\x1B\x0A\x08outbound\x12\x0Bshadowsocks\x90\xFF)\x01\"L\x0A\x11CipherTypeWrapper\x127\x0A\x05value\x18\x01 \x01(\x0E2(.v2ray.core.proxy.shadowsocks.CipherTypeB\x96\x01\x0A+com.v2ray.core.proxy.shadowsocks.simplifiedP\x01Z;github.com/v2fly/v2ray-core/v5/proxy/shadowsocks/simplified\xAA\x02'V2Ray.Core.Proxy.Shadowsocks.Simplifiedb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

