<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/stats/command/command.proto

namespace GPBMetadata\App\Stats\Command;

class Command
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD5\x08\x0A\x1Fapp/stats/command/command.proto\x12\x1Cv2ray.core.app.stats.command\".\x0A\x0FGetStatsRequest\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0D\x0A\x05reset\x18\x02 \x01(\x08\"#\x0A\x04Stat\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x03\"D\x0A\x10GetStatsResponse\x120\x0A\x04stat\x18\x01 \x01(\x0B2\".v2ray.core.app.stats.command.Stat\"U\x0A\x11QueryStatsRequest\x12\x0F\x0A\x07pattern\x18\x01 \x01(\x09\x12\x0D\x0A\x05reset\x18\x02 \x01(\x08\x12\x10\x0A\x08patterns\x18\x03 \x03(\x09\x12\x0E\x0A\x06regexp\x18\x04 \x01(\x08\"F\x0A\x12QueryStatsResponse\x120\x0A\x04stat\x18\x01 \x03(\x0B2\".v2ray.core.app.stats.command.Stat\"\x11\x0A\x0FSysStatsRequest\"\xC2\x01\x0A\x10SysStatsResponse\x12\x14\x0A\x0CNumGoroutine\x18\x01 \x01(\x0D\x12\x0D\x0A\x05NumGC\x18\x02 \x01(\x0D\x12\x0D\x0A\x05Alloc\x18\x03 \x01(\x04\x12\x12\x0A\x0ATotalAlloc\x18\x04 \x01(\x04\x12\x0B\x0A\x03Sys\x18\x05 \x01(\x04\x12\x0F\x0A\x07Mallocs\x18\x06 \x01(\x04\x12\x0D\x0A\x05Frees\x18\x07 \x01(\x04\x12\x13\x0A\x0BLiveObjects\x18\x08 \x01(\x04\x12\x14\x0A\x0CPauseTotalNs\x18\x09 \x01(\x04\x12\x0E\x0A\x06Uptime\x18\x0A \x01(\x0D\"\"\x0A\x06Config:\x18\x82\xB5\x18\x14\x0A\x0Bgrpcservice\x12\x05stats2\xDE\x02\x0A\x0CStatsService\x12k\x0A\x08GetStats\x12-.v2ray.core.app.stats.command.GetStatsRequest\x1A..v2ray.core.app.stats.command.GetStatsResponse\"\x00\x12q\x0A\x0AQueryStats\x12/.v2ray.core.app.stats.command.QueryStatsRequest\x1A0.v2ray.core.app.stats.command.QueryStatsResponse\"\x00\x12n\x0A\x0BGetSysStats\x12-.v2ray.core.app.stats.command.SysStatsRequest\x1A..v2ray.core.app.stats.command.SysStatsResponse\"\x00Bu\x0A com.v2ray.core.app.stats.commandP\x01Z0github.com/v2fly/v2ray-core/v5/app/stats/command\xAA\x02\x1CV2Ray.Core.App.Stats.Commandb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

