<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vless/inbound/config.proto

namespace GPBMetadata\Proxy\Vless\Inbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\User::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x83\x04\x0A proxy/vless/inbound/config.proto\x12\x1Ev2ray.core.proxy.vless.inbound\x1A common/protoext/extensions.proto\"P\x0A\x08Fallback\x12\x0C\x0A\x04alpn\x18\x01 \x01(\x09\x12\x0C\x0A\x04path\x18\x02 \x01(\x09\x12\x0C\x0A\x04type\x18\x03 \x01(\x09\x12\x0C\x0A\x04dest\x18\x04 \x01(\x09\x12\x0C\x0A\x04xver\x18\x05 \x01(\x04\"\x8C\x01\x0A\x06Config\x121\x0A\x07clients\x18\x01 \x03(\x0B2 .v2ray.core.common.protocol.User\x12\x12\x0A\x0Adecryption\x18\x02 \x01(\x09\x12;\x0A\x09fallbacks\x18\x03 \x03(\x0B2(.v2ray.core.proxy.vless.inbound.Fallback\"7\x0A\x10SimplifiedConfig\x12\x0D\x0A\x05users\x18\x01 \x03(\x09:\x14\x82\xB5\x18\x10\x0A\x07inbound\x12\x05vlessB{\x0A\"com.v2ray.core.proxy.vless.inboundP\x01Z2github.com/v2fly/v2ray-core/v5/proxy/vless/inbound\xAA\x02\x1EV2Ray.Core.Proxy.Vless.Inboundb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

