<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vmess/account.proto

namespace GPBMetadata\Proxy\Vmess;

class Account
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\Headers::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA8\x02\x0A\x19proxy/vmess/account.proto\x12\x16v2ray.core.proxy.vmess\"\x85\x01\x0A\x07Account\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12\x10\x0A\x08alter_id\x18\x02 \x01(\x0D\x12E\x0A\x11security_settings\x18\x03 \x01(\x0B2*.v2ray.core.common.protocol.SecurityConfig\x12\x15\x0A\x0Dtests_enabled\x18\x04 \x01(\x09Bc\x0A\x1Acom.v2ray.core.proxy.vmessP\x01Z*github.com/v2fly/v2ray-core/v5/proxy/vmess\xAA\x02\x16V2Ray.Core.Proxy.Vmessb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

