<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/subscription/specs/abstract_spec.proto

namespace GPBMetadata\App\Subscription\Specs;

class AbstractSpec
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB7\x07\x0A*app/subscription/specs/abstract_spec.proto\x12!v2ray.core.app.subscription.specs\"\xE0\x01\x0A\x13ServerConfiguration\x12\x10\x0A\x08protocol\x18\x01 \x01(\x09\x12/\x0A\x11protocol_settings\x18\x02 \x01(\x0B2\x14.google.protobuf.Any\x12\x11\x0A\x09transport\x18\x03 \x01(\x09\x120\x0A\x12transport_settings\x18\x04 \x01(\x0B2\x14.google.protobuf.Any\x12\x10\x0A\x08security\x18\x05 \x01(\x09\x12/\x0A\x11security_settings\x18\x06 \x01(\x0B2\x14.google.protobuf.Any\"\x83\x02\x0A\x18SubscriptionServerConfig\x12\x0A\x0A\x02id\x18\x01 \x01(\x09\x12[\x0A\x08metadata\x18\x02 \x03(\x0B2I.v2ray.core.app.subscription.specs.SubscriptionServerConfig.MetadataEntry\x12M\x0A\x0Dconfiguration\x18\x03 \x01(\x0B26.v2ray.core.app.subscription.specs.ServerConfiguration\x1A/\x0A\x0DMetadataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01\"\xED\x01\x0A\x14SubscriptionDocument\x12W\x0A\x08metadata\x18\x02 \x03(\x0B2E.v2ray.core.app.subscription.specs.SubscriptionDocument.MetadataEntry\x12K\x0A\x06server\x18\x03 \x03(\x0B2;.v2ray.core.app.subscription.specs.SubscriptionServerConfig\x1A/\x0A\x0DMetadataEntry\x12\x0B\x0A\x03key\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x01(\x09:\x028\x01B\x84\x01\x0A%com.v2ray.core.app.subscription.specsP\x01Z5github.com/v2fly/v2ray-core/v5/app/subscription/specs\xAA\x02!V2Ray.Core.App.Subscription.Specsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

