<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/protoext/testing/test.proto

namespace GPBMetadata\Common\Protoext\Testing;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xA3\x02\x0A\"common/protoext/testing/test.proto\x12\"v2ray.core.common.protoext.testing\"J\x0A\x0ETestingMessage\x12%\x0A\x0Atest_field\x18\x01 \x01(\x09B\x11\x82\xB5\x18\x0D\x12\x04test\x12\x05test2:\x11\x82\xB5\x18\x0D\x0A\x04demo\x0A\x05demo2B\x84\x01\x0A&com.v2ray.core.common.protoext.testingP\x01Z3github.com/v2fly/v2ray-core/common/protoext/testing\xAA\x02\"V2Ray.Core.Common.ProtoExt.Testingb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

