<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/subscription/config.proto

namespace GPBMetadata\App\Subscription;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x04\x0A\x1Dapp/subscription/config.proto\x12\x1Bv2ray.core.app.subscription\"w\x0A\x0CImportSource\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0B\x0A\x03url\x18\x02 \x01(\x09\x12\x12\x0A\x0Atag_prefix\x18\x03 \x01(\x09\x12\x18\x0A\x10import_using_tag\x18\x04 \x01(\x09\x12\x1E\x0A\x16default_expire_seconds\x18\x05 \x01(\x04\"\xD5\x01\x0A\x06Config\x12:\x0A\x07imports\x18\x01 \x03(\x0B2).v2ray.core.app.subscription.ImportSource\x12#\x0A\x1Bnonnative_converter_overlay\x18\x02 \x01(\x0C\x12M\x0A nonnative_converter_overlay_file\x18\x82\xEE\x05 \x01(\x09B!\x82\xB5\x18\x1D\"\x1Bnonnative_converter_overlay:\x1B\x82\xB5\x18\x17\x0A\x07service\x12\x0CsubscriptionBr\x0A\x1Fcom.v2ray.core.app.subscriptionP\x01Z/github.com/v2fly/v2ray-core/v5/app/subscription\xAA\x02\x1BV2Ray.Core.App.Subscriptionb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

