<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/headers/http/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Http;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF9\x07\x0A,transport/internet/headers/http/config.proto\x12*v2ray.core.transport.internet.headers.http\"%\x0A\x06Header\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x0D\x0A\x05value\x18\x02 \x03(\x09\"\x18\x0A\x07Version\x12\x0D\x0A\x05value\x18\x01 \x01(\x09\"\x17\x0A\x06Method\x12\x0D\x0A\x05value\x18\x01 \x01(\x09\"\xEA\x01\x0A\x0DRequestConfig\x12D\x0A\x07version\x18\x01 \x01(\x0B23.v2ray.core.transport.internet.headers.http.Version\x12B\x0A\x06method\x18\x02 \x01(\x0B22.v2ray.core.transport.internet.headers.http.Method\x12\x0B\x0A\x03uri\x18\x03 \x03(\x09\x12B\x0A\x06header\x18\x04 \x03(\x0B22.v2ray.core.transport.internet.headers.http.Header\"&\x0A\x06Status\x12\x0C\x0A\x04code\x18\x01 \x01(\x09\x12\x0E\x0A\x06reason\x18\x02 \x01(\x09\"\xDE\x01\x0A\x0EResponseConfig\x12D\x0A\x07version\x18\x01 \x01(\x0B23.v2ray.core.transport.internet.headers.http.Version\x12B\x0A\x06status\x18\x02 \x01(\x0B22.v2ray.core.transport.internet.headers.http.Status\x12B\x0A\x06header\x18\x03 \x03(\x0B22.v2ray.core.transport.internet.headers.http.Header\"\xA2\x01\x0A\x06Config\x12J\x0A\x07request\x18\x01 \x01(\x0B29.v2ray.core.transport.internet.headers.http.RequestConfig\x12L\x0A\x08response\x18\x02 \x01(\x0B2:.v2ray.core.transport.internet.headers.http.ResponseConfigB\x9F\x01\x0A.com.v2ray.core.transport.internet.headers.httpP\x01Z>github.com/v2fly/v2ray-core/v5/transport/internet/headers/http\xAA\x02*V2Ray.Core.Transport.Internet.Headers.Httpb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

