<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/tls/utls/config.proto

namespace GPBMetadata\Transport\Internet\Tls\Utls;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Transport\Internet\Tls\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB5\x04\x0A(transport/internet/tls/utls/config.proto\x12&v2ray.core.transport.internet.tls.utls\x1A#transport/internet/tls/config.proto\"\xC9\x01\x0A\x06Config\x12=\x0A\x0Atls_config\x18\x01 \x01(\x0B2).v2ray.core.transport.internet.tls.Config\x12\x0F\x0A\x07imitate\x18\x02 \x01(\x09\x12\x0D\x0A\x05noSNI\x18\x03 \x01(\x08\x12F\x0A\x0Aforce_alpn\x18\x04 \x01(\x0E22.v2ray.core.transport.internet.tls.utls.ForcedALPN:\x18\x82\xB5\x18\x14\x0A\x08security\x12\x04utls\x90\xFF)\x01*R\x0A\x0AForcedALPN\x12&\x0A\"TRANSPORT_PREFERENCE_TAKE_PRIORITY\x10\x00\x12\x0B\x0A\x07NO_ALPN\x10\x01\x12\x0F\x0A\x0BUTLS_PRESET\x10\x02B\x93\x01\x0A*com.v2ray.core.transport.internet.tls.utlsP\x01Z:github.com/v2fly/v2ray-core/v5/transport/internet/tls/utls\xAA\x02&V2Ray.Core.Transport.Internet.Tls.UTlsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

