<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/config.proto

namespace V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.router.BalancingRule</code>
 */
class BalancingRule extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>repeated string outbound_selector = 2;</code>
     */
    private $outbound_selector;
    /**
     * Generated from protobuf field <code>string strategy = 3;</code>
     */
    protected $strategy = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Any strategy_settings = 4;</code>
     */
    protected $strategy_settings = null;
    /**
     * Generated from protobuf field <code>string fallback_tag = 5;</code>
     */
    protected $fallback_tag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $outbound_selector
     *     @type string $strategy
     *     @type \Google\Protobuf\Any $strategy_settings
     *     @type string $fallback_tag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string outbound_selector = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getOutboundSelector()
    {
        return $this->outbound_selector;
    }

    /**
     * Generated from protobuf field <code>repeated string outbound_selector = 2;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setOutboundSelector($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->outbound_selector = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string strategy = 3;</code>
     * @return string
     */
    public function getStrategy()
    {
        return $this->strategy;
    }

    /**
     * Generated from protobuf field <code>string strategy = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStrategy($var)
    {
        GPBUtil::checkString($var, True);
        $this->strategy = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any strategy_settings = 4;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getStrategySettings()
    {
        return $this->strategy_settings;
    }

    public function hasStrategySettings()
    {
        return isset($this->strategy_settings);
    }

    public function clearStrategySettings()
    {
        unset($this->strategy_settings);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any strategy_settings = 4;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setStrategySettings($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->strategy_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string fallback_tag = 5;</code>
     * @return string
     */
    public function getFallbackTag()
    {
        return $this->fallback_tag;
    }

    /**
     * Generated from protobuf field <code>string fallback_tag = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFallbackTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->fallback_tag = $var;

        return $this;
    }

}

