<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/config.proto

namespace V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.router.RoutingRule</code>
 */
class RoutingRule extends \Google\Protobuf\Internal\Message
{
    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
     */
    private $domain;
    /**
     * List of CIDRs for target IP address matching.
     * Deprecated. Use geoip below.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 3 [deprecated = true];</code>
     * @deprecated
     */
    private $cidr;
    /**
     * List of GeoIPs for target IP address matching. If this entry exists, the
     * cidr above will have no effect. GeoIP fields with the same country code are
     * supposed to contain exactly same content. They will be merged during
     * runtime. For customized GeoIPs, please leave country code empty.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP geoip = 10;</code>
     */
    private $geoip;
    /**
     * A range of port [from, to]. If the destination port is in this range, this
     * rule takes effect. Deprecated. Use port_list.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortRange port_range = 4 [deprecated = true];</code>
     * @deprecated
     */
    protected $port_range = null;
    /**
     * List of ports.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList port_list = 14;</code>
     */
    protected $port_list = null;
    /**
     * List of networks. Deprecated. Use networks.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.NetworkList network_list = 5 [deprecated = true];</code>
     * @deprecated
     */
    protected $network_list = null;
    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network networks = 13;</code>
     */
    private $networks;
    /**
     * List of CIDRs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR source_cidr = 6 [deprecated = true];</code>
     * @deprecated
     */
    private $source_cidr;
    /**
     * List of GeoIPs for source IP address matching. If this entry exists, the
     * source_cidr above will have no effect.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP source_geoip = 11;</code>
     */
    private $source_geoip;
    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList source_port_list = 16;</code>
     */
    protected $source_port_list = null;
    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     */
    private $user_email;
    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     */
    private $inbound_tag;
    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     */
    private $protocol;
    /**
     * Generated from protobuf field <code>string attributes = 15;</code>
     */
    protected $attributes = '';
    /**
     * Generated from protobuf field <code>string domain_matcher = 17;</code>
     */
    protected $domain_matcher = '';
    /**
     * geo_domain instruct simplified config loader to load geo domain rule and fill in domain field.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoSite geo_domain = 68001;</code>
     */
    private $geo_domain;
    protected $target_tag;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tag
     *           Tag of outbound that this rule is pointing to.
     *     @type string $balancing_tag
     *           Tag of routing balancer.
     *     @type array<\V2ray\Core\App\Router\Routercommon\Domain>|\Google\Protobuf\Internal\RepeatedField $domain
     *           List of domains for target domain matching.
     *     @type array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $cidr
     *           List of CIDRs for target IP address matching.
     *           Deprecated. Use geoip below.
     *     @type array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $geoip
     *           List of GeoIPs for target IP address matching. If this entry exists, the
     *           cidr above will have no effect. GeoIP fields with the same country code are
     *           supposed to contain exactly same content. They will be merged during
     *           runtime. For customized GeoIPs, please leave country code empty.
     *     @type \V2ray\Core\Common\Net\PortRange $port_range
     *           A range of port [from, to]. If the destination port is in this range, this
     *           rule takes effect. Deprecated. Use port_list.
     *     @type \V2ray\Core\Common\Net\PortList $port_list
     *           List of ports.
     *     @type \V2ray\Core\Common\Net\NetworkList $network_list
     *           List of networks. Deprecated. Use networks.
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $networks
     *           List of networks for matching.
     *     @type array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $source_cidr
     *           List of CIDRs for source IP address matching.
     *     @type array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $source_geoip
     *           List of GeoIPs for source IP address matching. If this entry exists, the
     *           source_cidr above will have no effect.
     *     @type \V2ray\Core\Common\Net\PortList $source_port_list
     *           List of ports for source port matching.
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $user_email
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $inbound_tag
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $protocol
     *     @type string $attributes
     *     @type string $domain_matcher
     *     @type array<\V2ray\Core\App\Router\Routercommon\GeoSite>|\Google\Protobuf\Internal\RepeatedField $geo_domain
     *           geo_domain instruct simplified config loader to load geo domain rule and fill in domain field.
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Tag of outbound that this rule is pointing to.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->readOneof(1);
    }

    public function hasTag()
    {
        return $this->hasOneof(1);
    }

    /**
     * Tag of outbound that this rule is pointing to.
     *
     * Generated from protobuf field <code>string tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Tag of routing balancer.
     *
     * Generated from protobuf field <code>string balancing_tag = 12;</code>
     * @return string
     */
    public function getBalancingTag()
    {
        return $this->readOneof(12);
    }

    public function hasBalancingTag()
    {
        return $this->hasOneof(12);
    }

    /**
     * Tag of routing balancer.
     *
     * Generated from protobuf field <code>string balancing_tag = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setBalancingTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->writeOneof(12, $var);

        return $this;
    }

    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDomain()
    {
        return $this->domain;
    }

    /**
     * List of domains for target domain matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.Domain domain = 2;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\Domain>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\Domain::class);
        $this->domain = $arr;

        return $this;
    }

    /**
     * List of CIDRs for target IP address matching.
     * Deprecated. Use geoip below.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 3 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     * @deprecated
     */
    public function getCidr()
    {
        @trigger_error('cidr is deprecated.', E_USER_DEPRECATED);
        return $this->cidr;
    }

    /**
     * List of CIDRs for target IP address matching.
     * Deprecated. Use geoip below.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR cidr = 3 [deprecated = true];</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @deprecated
     */
    public function setCidr($var)
    {
        @trigger_error('cidr is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\CIDR::class);
        $this->cidr = $arr;

        return $this;
    }

    /**
     * List of GeoIPs for target IP address matching. If this entry exists, the
     * cidr above will have no effect. GeoIP fields with the same country code are
     * supposed to contain exactly same content. They will be merged during
     * runtime. For customized GeoIPs, please leave country code empty.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP geoip = 10;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeoip()
    {
        return $this->geoip;
    }

    /**
     * List of GeoIPs for target IP address matching. If this entry exists, the
     * cidr above will have no effect. GeoIP fields with the same country code are
     * supposed to contain exactly same content. They will be merged during
     * runtime. For customized GeoIPs, please leave country code empty.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP geoip = 10;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeoip($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\GeoIP::class);
        $this->geoip = $arr;

        return $this;
    }

    /**
     * A range of port [from, to]. If the destination port is in this range, this
     * rule takes effect. Deprecated. Use port_list.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortRange port_range = 4 [deprecated = true];</code>
     * @return \V2ray\Core\Common\Net\PortRange|null
     * @deprecated
     */
    public function getPortRange()
    {
        @trigger_error('port_range is deprecated.', E_USER_DEPRECATED);
        return $this->port_range;
    }

    public function hasPortRange()
    {
        @trigger_error('port_range is deprecated.', E_USER_DEPRECATED);
        return isset($this->port_range);
    }

    public function clearPortRange()
    {
        @trigger_error('port_range is deprecated.', E_USER_DEPRECATED);
        unset($this->port_range);
    }

    /**
     * A range of port [from, to]. If the destination port is in this range, this
     * rule takes effect. Deprecated. Use port_list.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortRange port_range = 4 [deprecated = true];</code>
     * @param \V2ray\Core\Common\Net\PortRange $var
     * @return $this
     * @deprecated
     */
    public function setPortRange($var)
    {
        @trigger_error('port_range is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\PortRange::class);
        $this->port_range = $var;

        return $this;
    }

    /**
     * List of ports.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList port_list = 14;</code>
     * @return \V2ray\Core\Common\Net\PortList|null
     */
    public function getPortList()
    {
        return $this->port_list;
    }

    public function hasPortList()
    {
        return isset($this->port_list);
    }

    public function clearPortList()
    {
        unset($this->port_list);
    }

    /**
     * List of ports.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList port_list = 14;</code>
     * @param \V2ray\Core\Common\Net\PortList $var
     * @return $this
     */
    public function setPortList($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\PortList::class);
        $this->port_list = $var;

        return $this;
    }

    /**
     * List of networks. Deprecated. Use networks.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.NetworkList network_list = 5 [deprecated = true];</code>
     * @return \V2ray\Core\Common\Net\NetworkList|null
     * @deprecated
     */
    public function getNetworkList()
    {
        @trigger_error('network_list is deprecated.', E_USER_DEPRECATED);
        return $this->network_list;
    }

    public function hasNetworkList()
    {
        @trigger_error('network_list is deprecated.', E_USER_DEPRECATED);
        return isset($this->network_list);
    }

    public function clearNetworkList()
    {
        @trigger_error('network_list is deprecated.', E_USER_DEPRECATED);
        unset($this->network_list);
    }

    /**
     * List of networks. Deprecated. Use networks.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.NetworkList network_list = 5 [deprecated = true];</code>
     * @param \V2ray\Core\Common\Net\NetworkList $var
     * @return $this
     * @deprecated
     */
    public function setNetworkList($var)
    {
        @trigger_error('network_list is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\NetworkList::class);
        $this->network_list = $var;

        return $this;
    }

    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network networks = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetworks()
    {
        return $this->networks;
    }

    /**
     * List of networks for matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network networks = 13;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetworks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \V2ray\Core\Common\Net\Network::class);
        $this->networks = $arr;

        return $this;
    }

    /**
     * List of CIDRs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR source_cidr = 6 [deprecated = true];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     * @deprecated
     */
    public function getSourceCidr()
    {
        @trigger_error('source_cidr is deprecated.', E_USER_DEPRECATED);
        return $this->source_cidr;
    }

    /**
     * List of CIDRs for source IP address matching.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR source_cidr = 6 [deprecated = true];</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     * @deprecated
     */
    public function setSourceCidr($var)
    {
        @trigger_error('source_cidr is deprecated.', E_USER_DEPRECATED);
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\CIDR::class);
        $this->source_cidr = $arr;

        return $this;
    }

    /**
     * List of GeoIPs for source IP address matching. If this entry exists, the
     * source_cidr above will have no effect.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP source_geoip = 11;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSourceGeoip()
    {
        return $this->source_geoip;
    }

    /**
     * List of GeoIPs for source IP address matching. If this entry exists, the
     * source_cidr above will have no effect.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP source_geoip = 11;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSourceGeoip($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\GeoIP::class);
        $this->source_geoip = $arr;

        return $this;
    }

    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList source_port_list = 16;</code>
     * @return \V2ray\Core\Common\Net\PortList|null
     */
    public function getSourcePortList()
    {
        return $this->source_port_list;
    }

    public function hasSourcePortList()
    {
        return isset($this->source_port_list);
    }

    public function clearSourcePortList()
    {
        unset($this->source_port_list);
    }

    /**
     * List of ports for source port matching.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.PortList source_port_list = 16;</code>
     * @param \V2ray\Core\Common\Net\PortList $var
     * @return $this
     */
    public function setSourcePortList($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\PortList::class);
        $this->source_port_list = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getUserEmail()
    {
        return $this->user_email;
    }

    /**
     * Generated from protobuf field <code>repeated string user_email = 7;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setUserEmail($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->user_email = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInboundTag()
    {
        return $this->inbound_tag;
    }

    /**
     * Generated from protobuf field <code>repeated string inbound_tag = 8;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInboundTag($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->inbound_tag = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getProtocol()
    {
        return $this->protocol;
    }

    /**
     * Generated from protobuf field <code>repeated string protocol = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setProtocol($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->protocol = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string attributes = 15;</code>
     * @return string
     */
    public function getAttributes()
    {
        return $this->attributes;
    }

    /**
     * Generated from protobuf field <code>string attributes = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setAttributes($var)
    {
        GPBUtil::checkString($var, True);
        $this->attributes = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string domain_matcher = 17;</code>
     * @return string
     */
    public function getDomainMatcher()
    {
        return $this->domain_matcher;
    }

    /**
     * Generated from protobuf field <code>string domain_matcher = 17;</code>
     * @param string $var
     * @return $this
     */
    public function setDomainMatcher($var)
    {
        GPBUtil::checkString($var, True);
        $this->domain_matcher = $var;

        return $this;
    }

    /**
     * geo_domain instruct simplified config loader to load geo domain rule and fill in domain field.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoSite geo_domain = 68001;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGeoDomain()
    {
        return $this->geo_domain;
    }

    /**
     * geo_domain instruct simplified config loader to load geo domain rule and fill in domain field.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoSite geo_domain = 68001;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\GeoSite>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGeoDomain($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\GeoSite::class);
        $this->geo_domain = $arr;

        return $this;
    }

    /**
     * @return string
     */
    public function getTargetTag()
    {
        return $this->whichOneof("target_tag");
    }

}

