<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/config.proto

namespace V2ray\Core\App\Router;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.router.StrategyRandomConfig</code>
 */
class StrategyRandomConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string observer_tag = 7;</code>
     */
    protected $observer_tag = '';
    /**
     * Generated from protobuf field <code>bool alive_only = 8;</code>
     */
    protected $alive_only = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $observer_tag
     *     @type bool $alive_only
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string observer_tag = 7;</code>
     * @return string
     */
    public function getObserverTag()
    {
        return $this->observer_tag;
    }

    /**
     * Generated from protobuf field <code>string observer_tag = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setObserverTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->observer_tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool alive_only = 8;</code>
     * @return bool
     */
    public function getAliveOnly()
    {
        return $this->alive_only;
    }

    /**
     * Generated from protobuf field <code>bool alive_only = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setAliveOnly($var)
    {
        GPBUtil::checkBool($var);
        $this->alive_only = $var;

        return $this;
    }

}

