<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/shadowsocks/config.proto

namespace V2ray\Core\Proxy\Shadowsocks;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.shadowsocks.ServerConfig</code>
 */
class ServerConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     *
     * Generated from protobuf field <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @deprecated
     */
    protected $udp_enabled = false;
    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.User user = 2;</code>
     */
    protected $user = null;
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     */
    private $network;
    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     */
    protected $packet_encoding = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $udp_enabled
     *           UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     *           Deprecated. Use 'network' field.
     *     @type \V2ray\Core\Common\Protocol\User $user
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $network
     *     @type int $packet_encoding
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Shadowsocks\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     *
     * Generated from protobuf field <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @return bool
     * @deprecated
     */
    public function getUdpEnabled()
    {
        @trigger_error('udp_enabled is deprecated.', E_USER_DEPRECATED);
        return $this->udp_enabled;
    }

    /**
     * UdpEnabled specified whether or not to enable UDP for Shadowsocks.
     * Deprecated. Use 'network' field.
     *
     * Generated from protobuf field <code>bool udp_enabled = 1 [deprecated = true];</code>
     * @param bool $var
     * @return $this
     * @deprecated
     */
    public function setUdpEnabled($var)
    {
        @trigger_error('udp_enabled is deprecated.', E_USER_DEPRECATED);
        GPBUtil::checkBool($var);
        $this->udp_enabled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.User user = 2;</code>
     * @return \V2ray\Core\Common\Protocol\User|null
     */
    public function getUser()
    {
        return $this->user;
    }

    public function hasUser()
    {
        return isset($this->user);
    }

    public function clearUser()
    {
        unset($this->user);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.User user = 2;</code>
     * @param \V2ray\Core\Common\Protocol\User $var
     * @return $this
     */
    public function setUser($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Protocol\User::class);
        $this->user = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 3;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetwork($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \V2ray\Core\Common\Net\Network::class);
        $this->network = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     * @return int
     */
    public function getPacketEncoding()
    {
        return $this->packet_encoding;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPacketEncoding($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Net\Packetaddr\PacketAddrType::class);
        $this->packet_encoding = $var;

        return $this;
    }

}

