<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/blackhole/config.proto

namespace GPBMetadata\Proxy\Blackhole;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xD6\x02\x0A\x1Cproxy/blackhole/config.proto\x12\x1Av2ray.core.proxy.blackhole\x1A common/protoext/extensions.proto\"\x0E\x0A\x0CNoneResponse\"\x0E\x0A\x0CHTTPResponse\"0\x0A\x06Config\x12&\x0A\x08response\x18\x01 \x01(\x0B2\x14.google.protobuf.Any\"-\x0A\x10SimplifiedConfig:\x19\x82\xB5\x18\x15\x0A\x08outbound\x12\x09blackholeBo\x0A\x1Ecom.v2ray.core.proxy.blackholeP\x01Z.github.com/v2fly/v2ray-core/v5/proxy/blackhole\xAA\x02\x1AV2Ray.Core.Proxy.Blackholeb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

