<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/burst/config.proto

namespace GPBMetadata\App\Observatory\Burst;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xDA\x03\x0A\"app/observatory/burst/config.proto\x12 v2ray.core.app.observatory.burst\"\x8C\x01\x0A\x06Config\x12\x18\x0A\x10subject_selector\x18\x02 \x03(\x09\x12G\x0A\x0Bping_config\x18\x03 \x01(\x0B22.v2ray.core.app.observatory.burst.HealthPingConfig:\x1F\x82\xB5\x18\x1B\x0A\x07service\x12\x10burstObservatory\"w\x0A\x10HealthPingConfig\x12\x13\x0A\x0Bdestination\x18\x01 \x01(\x09\x12\x14\x0A\x0Cconnectivity\x18\x02 \x01(\x09\x12\x10\x0A\x08interval\x18\x03 \x01(\x03\x12\x15\x0A\x0DsamplingCount\x18\x04 \x01(\x05\x12\x0F\x0A\x07timeout\x18\x05 \x01(\x03B\x81\x01\x0A\$com.v2ray.core.app.observatory.burstP\x01Z4github.com/v2fly/v2ray-core/v5/app/observatory/burst\xAA\x02 V2Ray.Core.App.Observatory.Burstb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

