<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/observatory/command/command.proto

namespace V2ray\Core\App\Observatory\Command;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.observatory.command.GetOutboundStatusRequest</code>
 */
class GetOutboundStatusRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Tag = 1;</code>
     */
    protected $Tag = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Tag
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Observatory\Command\Command::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Tag = 1;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->Tag;
    }

    /**
     * Generated from protobuf field <code>string Tag = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->Tag = $var;

        return $this;
    }

}

