<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/tun/config.proto

namespace V2ray\Core\App\Tun;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.tun.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string name = 1;</code>
     */
    protected $name = '';
    /**
     * Generated from protobuf field <code>uint32 mtu = 2;</code>
     */
    protected $mtu = 0;
    /**
     * Generated from protobuf field <code>uint32 user_level = 3;</code>
     */
    protected $user_level = 0;
    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     */
    protected $packet_encoding = 0;
    /**
     * Generated from protobuf field <code>string tag = 5;</code>
     */
    protected $tag = '';
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR ips = 6;</code>
     */
    private $ips;
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR routes = 7;</code>
     */
    private $routes;
    /**
     * Generated from protobuf field <code>bool enable_promiscuous_mode = 8;</code>
     */
    protected $enable_promiscuous_mode = false;
    /**
     * Generated from protobuf field <code>bool enable_spoofing = 9;</code>
     */
    protected $enable_spoofing = false;
    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 10;</code>
     */
    protected $socket_settings = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SniffingConfig sniffing_settings = 11;</code>
     */
    protected $sniffing_settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $name
     *     @type int $mtu
     *     @type int $user_level
     *     @type int $packet_encoding
     *     @type string $tag
     *     @type array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $ips
     *     @type array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $routes
     *     @type bool $enable_promiscuous_mode
     *     @type bool $enable_spoofing
     *     @type \V2ray\Core\Transport\Internet\SocketConfig $socket_settings
     *     @type \V2ray\Core\App\Proxyman\SniffingConfig $sniffing_settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Tun\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Generated from protobuf field <code>string name = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 mtu = 2;</code>
     * @return int
     */
    public function getMtu()
    {
        return $this->mtu;
    }

    /**
     * Generated from protobuf field <code>uint32 mtu = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMtu($var)
    {
        GPBUtil::checkUint32($var);
        $this->mtu = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 3;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     * @return int
     */
    public function getPacketEncoding()
    {
        return $this->packet_encoding;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.net.packetaddr.PacketAddrType packet_encoding = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setPacketEncoding($var)
    {
        GPBUtil::checkEnum($var, \V2ray\Core\Net\Packetaddr\PacketAddrType::class);
        $this->packet_encoding = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tag = 5;</code>
     * @return string
     */
    public function getTag()
    {
        return $this->tag;
    }

    /**
     * Generated from protobuf field <code>string tag = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTag($var)
    {
        GPBUtil::checkString($var, True);
        $this->tag = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR ips = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getIps()
    {
        return $this->ips;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR ips = 6;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setIps($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\CIDR::class);
        $this->ips = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR routes = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.CIDR routes = 7;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\CIDR>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setRoutes($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\CIDR::class);
        $this->routes = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_promiscuous_mode = 8;</code>
     * @return bool
     */
    public function getEnablePromiscuousMode()
    {
        return $this->enable_promiscuous_mode;
    }

    /**
     * Generated from protobuf field <code>bool enable_promiscuous_mode = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnablePromiscuousMode($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_promiscuous_mode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool enable_spoofing = 9;</code>
     * @return bool
     */
    public function getEnableSpoofing()
    {
        return $this->enable_spoofing;
    }

    /**
     * Generated from protobuf field <code>bool enable_spoofing = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setEnableSpoofing($var)
    {
        GPBUtil::checkBool($var);
        $this->enable_spoofing = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 10;</code>
     * @return \V2ray\Core\Transport\Internet\SocketConfig|null
     */
    public function getSocketSettings()
    {
        return $this->socket_settings;
    }

    public function hasSocketSettings()
    {
        return isset($this->socket_settings);
    }

    public function clearSocketSettings()
    {
        unset($this->socket_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.transport.internet.SocketConfig socket_settings = 10;</code>
     * @param \V2ray\Core\Transport\Internet\SocketConfig $var
     * @return $this
     */
    public function setSocketSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Transport\Internet\SocketConfig::class);
        $this->socket_settings = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SniffingConfig sniffing_settings = 11;</code>
     * @return \V2ray\Core\App\Proxyman\SniffingConfig|null
     */
    public function getSniffingSettings()
    {
        return $this->sniffing_settings;
    }

    public function hasSniffingSettings()
    {
        return isset($this->sniffing_settings);
    }

    public function clearSniffingSettings()
    {
        unset($this->sniffing_settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.proxyman.SniffingConfig sniffing_settings = 11;</code>
     * @param \V2ray\Core\App\Proxyman\SniffingConfig $var
     * @return $this
     */
    public function setSniffingSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Proxyman\SniffingConfig::class);
        $this->sniffing_settings = $var;

        return $this;
    }

}

