<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/trojan/config.proto

namespace GPBMetadata\Proxy\Trojan;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\User::initOnce();
        \GPBMetadata\Common\Protocol\ServerSpec::initOnce();
        \GPBMetadata\Common\Net\Packetaddr\Config::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE2\x04\x0A\x19proxy/trojan/config.proto\x12\x17v2ray.core.proxy.trojan\x1A!common/protocol/server_spec.proto\x1A\"common/net/packetaddr/config.proto\"\x1B\x0A\x07Account\x12\x10\x0A\x08password\x18\x01 \x01(\x09\"P\x0A\x08Fallback\x12\x0C\x0A\x04alpn\x18\x01 \x01(\x09\x12\x0C\x0A\x04path\x18\x02 \x01(\x09\x12\x0C\x0A\x04type\x18\x03 \x01(\x09\x12\x0C\x0A\x04dest\x18\x04 \x01(\x09\x12\x0C\x0A\x04xver\x18\x05 \x01(\x04\"J\x0A\x0CClientConfig\x12:\x0A\x06server\x18\x01 \x03(\x0B2*.v2ray.core.common.protocol.ServerEndpoint\"\xB9\x01\x0A\x0CServerConfig\x12/\x0A\x05users\x18\x01 \x03(\x0B2 .v2ray.core.common.protocol.User\x124\x0A\x09fallbacks\x18\x03 \x03(\x0B2!.v2ray.core.proxy.trojan.Fallback\x12B\x0A\x0Fpacket_encoding\x18\x04 \x01(\x0E2).v2ray.core.net.packetaddr.PacketAddrTypeBf\x0A\x1Bcom.v2ray.core.proxy.trojanP\x01Z+github.com/v2fly/v2ray-core/v5/proxy/trojan\xAA\x02\x17V2Ray.Core.Proxy.Trojanb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

