<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/taggedfeatures/skeleton.proto

namespace V2ray\Core\Common\Taggedfeatures;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.common.taggedfeatures.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> features = 1;</code>
     */
    private $features;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $features
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Taggedfeatures\Skeleton::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> features = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * Generated from protobuf field <code>map<string, .google.protobuf.Any> features = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setFeatures($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::MESSAGE, \Google\Protobuf\Any::class);
        $this->features = $arr;

        return $this;
    }

}

