<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/quic/config.proto

namespace V2ray\Core\Transport\Internet\Quic;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.quic.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string key = 1;</code>
     */
    protected $key = '';
    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.SecurityConfig security = 2;</code>
     */
    protected $security = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 3;</code>
     */
    protected $header = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $key
     *     @type \V2ray\Core\Common\Protocol\SecurityConfig $security
     *     @type \Google\Protobuf\Any $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Quic\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @return string
     */
    public function getKey()
    {
        return $this->key;
    }

    /**
     * Generated from protobuf field <code>string key = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setKey($var)
    {
        GPBUtil::checkString($var, True);
        $this->key = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.SecurityConfig security = 2;</code>
     * @return \V2ray\Core\Common\Protocol\SecurityConfig|null
     */
    public function getSecurity()
    {
        return $this->security;
    }

    public function hasSecurity()
    {
        return isset($this->security);
    }

    public function clearSecurity()
    {
        unset($this->security);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.common.protocol.SecurityConfig security = 2;</code>
     * @param \V2ray\Core\Common\Protocol\SecurityConfig $var
     * @return $this
     */
    public function setSecurity($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Protocol\SecurityConfig::class);
        $this->security = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 3;</code>
     * @return \Google\Protobuf\Any|null
     */
    public function getHeader()
    {
        return $this->header;
    }

    public function hasHeader()
    {
        return isset($this->header);
    }

    public function clearHeader()
    {
        unset($this->header);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Any header = 3;</code>
     * @param \Google\Protobuf\Any $var
     * @return $this
     */
    public function setHeader($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Any::class);
        $this->header = $var;

        return $this;
    }

}

