<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/subscription/specs/abstract_spec.proto

namespace V2ray\Core\App\Subscription\Specs;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.subscription.specs.SubscriptionDocument</code>
 */
class SubscriptionDocument extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
     */
    private $metadata;
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.specs.SubscriptionServerConfig server = 3;</code>
     */
    private $server;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $metadata
     *     @type array<\V2ray\Core\App\Subscription\Specs\SubscriptionServerConfig>|\Google\Protobuf\Internal\RepeatedField $server
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Subscription\Specs\AbstractSpec::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Generated from protobuf field <code>map<string, string> metadata = 2;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setMetadata($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->metadata = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.specs.SubscriptionServerConfig server = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.subscription.specs.SubscriptionServerConfig server = 3;</code>
     * @param array<\V2ray\Core\App\Subscription\Specs\SubscriptionServerConfig>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Subscription\Specs\SubscriptionServerConfig::class);
        $this->server = $arr;

        return $this;
    }

}

