<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/dispatcher/config.proto

namespace GPBMetadata\App\Dispatcher;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x8B\x02\x0A\x1Bapp/dispatcher/config.proto\x12\x19v2ray.core.app.dispatcher\"\x15\x0A\x0DSessionConfigJ\x04\x08\x01\x10\x02\"D\x0A\x06Config\x12:\x0A\x08settings\x18\x01 \x01(\x0B2(.v2ray.core.app.dispatcher.SessionConfigBl\x0A\x1Dcom.v2ray.core.app.dispatcherP\x01Z-github.com/v2fly/v2ray-core/v5/app/dispatcher\xAA\x02\x19V2Ray.Core.App.Dispatcherb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

