<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/browserforwarder/config.proto

namespace GPBMetadata\App\Browserforwarder;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x98\x02\x0A!app/browserforwarder/config.proto\x12\x1Fv2ray.core.app.browserforwarder\"J\x0A\x06Config\x12\x13\x0A\x0Blisten_addr\x18\x01 \x01(\x09\x12\x13\x0A\x0Blisten_port\x18\x02 \x01(\x05:\x16\x82\xB5\x18\x12\x0A\x07service\x12\x07browserB~\x0A#com.v2ray.core.app.browserforwarderP\x01Z3github.com/v2fly/v2ray-core/v5/app/browserforwarder\xAA\x02\x1FV2Ray.Core.App.Browserforwarderb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

