<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/instman/command/command.proto

namespace GPBMetadata\App\Instman\Command;

class Command
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xB6\x06\x0A!app/instman/command/command.proto\x12\x1Ev2ray.core.app.instman.command\"\x11\x0A\x0FListInstanceReq\" \x0A\x10ListInstanceResp\x12\x0C\x0A\x04name\x18\x01 \x03(\x09\"L\x0A\x0EAddInstanceReq\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\x12\x12\x0A\x0AconfigType\x18\x02 \x01(\x09\x12\x18\x0A\x10configContentB64\x18\x03 \x01(\x09\"\x11\x0A\x0FAddInstanceResp\" \x0A\x10StartInstanceReq\x12\x0C\x0A\x04name\x18\x01 \x01(\x09\"\x13\x0A\x11StartInstanceResp\"\$\x0A\x06Config:\x1A\x82\xB5\x18\x16\x0A\x0Bgrpcservice\x12\x07instman2\xF4\x02\x0A\x19InstanceManagementService\x12q\x0A\x0CListInstance\x12/.v2ray.core.app.instman.command.ListInstanceReq\x1A0.v2ray.core.app.instman.command.ListInstanceResp\x12n\x0A\x0BAddInstance\x12..v2ray.core.app.instman.command.AddInstanceReq\x1A/.v2ray.core.app.instman.command.AddInstanceResp\x12t\x0A\x0DStartInstance\x120.v2ray.core.app.instman.command.StartInstanceReq\x1A1.v2ray.core.app.instman.command.StartInstanceRespB\x7F\x0A&com.v2ray.core.app.observatory.instmanP\x01Z2github.com/v2fly/v2ray-core/v5/app/instman/command\xAA\x02\x1EV2Ray.Core.App.Instman.Commandb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

