<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/commander/config.proto

namespace V2ray\Core\App\Commander;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ReflectionConfig is the placeholder config for ReflectionService.
 *
 * Generated from protobuf message <code>v2ray.core.app.commander.ReflectionConfig</code>
 */
class ReflectionConfig extends \Google\Protobuf\Internal\Message
{

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Commander\Config::initOnce();
        parent::__construct($data);
    }

}

