<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/policy/config.proto

namespace V2ray\Core\App\Policy;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.policy.Policy</code>
 */
class Policy extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     */
    protected $timeout = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     */
    protected $stats = null;
    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     */
    protected $buffer = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\App\Policy\Policy\Timeout $timeout
     *     @type \V2ray\Core\App\Policy\Policy\Stats $stats
     *     @type \V2ray\Core\App\Policy\Policy\Buffer $buffer
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Policy\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     * @return \V2ray\Core\App\Policy\Policy\Timeout|null
     */
    public function getTimeout()
    {
        return $this->timeout;
    }

    public function hasTimeout()
    {
        return isset($this->timeout);
    }

    public function clearTimeout()
    {
        unset($this->timeout);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Timeout timeout = 1;</code>
     * @param \V2ray\Core\App\Policy\Policy\Timeout $var
     * @return $this
     */
    public function setTimeout($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Policy\Policy\Timeout::class);
        $this->timeout = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     * @return \V2ray\Core\App\Policy\Policy\Stats|null
     */
    public function getStats()
    {
        return $this->stats;
    }

    public function hasStats()
    {
        return isset($this->stats);
    }

    public function clearStats()
    {
        unset($this->stats);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Stats stats = 2;</code>
     * @param \V2ray\Core\App\Policy\Policy\Stats $var
     * @return $this
     */
    public function setStats($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Policy\Policy\Stats::class);
        $this->stats = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     * @return \V2ray\Core\App\Policy\Policy\Buffer|null
     */
    public function getBuffer()
    {
        return $this->buffer;
    }

    public function hasBuffer()
    {
        return isset($this->buffer);
    }

    public function clearBuffer()
    {
        unset($this->buffer);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.policy.Policy.Buffer buffer = 3;</code>
     * @param \V2ray\Core\App\Policy\Policy\Buffer $var
     * @return $this
     */
    public function setBuffer($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Policy\Policy\Buffer::class);
        $this->buffer = $var;

        return $this;
    }

}

