<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/log/log.proto

namespace GPBMetadata\Common\Log;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xDD\x01\x0A\x14common/log/log.proto\x12\x15v2ray.core.common.log*D\x0A\x08Severity\x12\x0B\x0A\x07Unknown\x10\x00\x12\x09\x0A\x05Error\x10\x01\x12\x0B\x0A\x07Warning\x10\x02\x12\x08\x0A\x04Info\x10\x03\x12\x09\x0A\x05Debug\x10\x04B`\x0A\x19com.v2ray.core.common.logP\x01Z)github.com/v2fly/v2ray-core/v5/common/log\xAA\x02\x15V2Ray.Core.Common.Logb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

