<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/instman/config.proto

namespace GPBMetadata\App\Instman;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC1\x01\x0A\x18app/instman/config.proto\x12\x16v2ray.core.app.instman\" \x0A\x06Config:\x16\x82\xB5\x18\x12\x0A\x07service\x12\x07instmanBc\x0A\x1Acom.v2ray.core.app.instmanP\x01Z*github.com/v2fly/v2ray-core/v5/app/instman\xAA\x02\x16V2Ray.Core.App.Instmanb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

