<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/headers/wechat/config.proto

namespace GPBMetadata\Transport\Internet\Headers\Wechat;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\x9D\x02\x0A.transport/internet/headers/wechat/config.proto\x12,v2ray.core.transport.internet.headers.wechat\"\x0D\x0A\x0BVideoConfigB\xA5\x01\x0A0com.v2ray.core.transport.internet.headers.wechatP\x01Z@github.com/v2fly/v2ray-core/v5/transport/internet/headers/wechat\xAA\x02,V2Ray.Core.Transport.Internet.Headers.Wechatb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

