<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/dispatcher/config.proto

namespace V2ray\Core\App\Dispatcher;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.dispatcher.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.v2ray.core.app.dispatcher.SessionConfig settings = 1;</code>
     */
    protected $settings = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\App\Dispatcher\SessionConfig $settings
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Dispatcher\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.dispatcher.SessionConfig settings = 1;</code>
     * @return \V2ray\Core\App\Dispatcher\SessionConfig|null
     */
    public function getSettings()
    {
        return $this->settings;
    }

    public function hasSettings()
    {
        return isset($this->settings);
    }

    public function clearSettings()
    {
        unset($this->settings);
    }

    /**
     * Generated from protobuf field <code>.v2ray.core.app.dispatcher.SessionConfig settings = 1;</code>
     * @param \V2ray\Core\App\Dispatcher\SessionConfig $var
     * @return $this
     */
    public function setSettings($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\App\Dispatcher\SessionConfig::class);
        $this->settings = $var;

        return $this;
    }

}

