<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/packetaddr/config.proto

namespace GPBMetadata\Common\Net\Packetaddr;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xF3\x01\x0A\"common/net/packetaddr/config.proto\x12\x19v2ray.core.net.packetaddr*&\x0A\x0EPacketAddrType\x12\x08\x0A\x04None\x10\x00\x12\x0A\x0A\x06Packet\x10\x01B\x81\x01\x0A\$com.v2ray.core.common.net.packetaddrP\x01Z4github.com/v2fly/v2ray-core/v5/common/net/packetaddr\xAA\x02 V2Ray.Core.Common.Net.Packetaddrb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

