<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/routercommon/common.proto

namespace V2ray\Core\App\Router\Routercommon;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * IP for routing decision, in CIDR form.
 *
 * Generated from protobuf message <code>v2ray.core.app.router.routercommon.CIDR</code>
 */
class CIDR extends \Google\Protobuf\Internal\Message
{
    /**
     * IP address, should be either 4 or 16 bytes.
     *
     * Generated from protobuf field <code>bytes ip = 1;</code>
     */
    protected $ip = '';
    /**
     * Number of leading ones in the network mask.
     *
     * Generated from protobuf field <code>uint32 prefix = 2;</code>
     */
    protected $prefix = 0;
    /**
     * Generated from protobuf field <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = {</code>
     */
    protected $ip_addr = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ip
     *           IP address, should be either 4 or 16 bytes.
     *     @type int $prefix
     *           Number of leading ones in the network mask.
     *     @type string $ip_addr
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Routercommon\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * IP address, should be either 4 or 16 bytes.
     *
     * Generated from protobuf field <code>bytes ip = 1;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     * IP address, should be either 4 or 16 bytes.
     *
     * Generated from protobuf field <code>bytes ip = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, False);
        $this->ip = $var;

        return $this;
    }

    /**
     * Number of leading ones in the network mask.
     *
     * Generated from protobuf field <code>uint32 prefix = 2;</code>
     * @return int
     */
    public function getPrefix()
    {
        return $this->prefix;
    }

    /**
     * Number of leading ones in the network mask.
     *
     * Generated from protobuf field <code>uint32 prefix = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setPrefix($var)
    {
        GPBUtil::checkUint32($var);
        $this->prefix = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @return string
     */
    public function getIpAddr()
    {
        return $this->ip_addr;
    }

    /**
     * Generated from protobuf field <code>string ip_addr = 68000 [(.v2ray.core.common.protoext.field_opt) = {</code>
     * @param string $var
     * @return $this
     */
    public function setIpAddr($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip_addr = $var;

        return $this;
    }

}

