<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/router/routercommon/common.proto

namespace V2ray\Core\App\Router\Routercommon;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.app.router.routercommon.GeoIPList</code>
 */
class GeoIPList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     */
    private $entry;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $entry
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\App\Router\Routercommon\Common::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntry()
    {
        return $this->entry;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.app.router.routercommon.GeoIP entry = 1;</code>
     * @param array<\V2ray\Core\App\Router\Routercommon\GeoIP>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntry($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\App\Router\Routercommon\GeoIP::class);
        $this->entry = $arr;

        return $this;
    }

}

