<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/dns/config.proto

namespace V2ray\Core\Proxy\Dns;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.proxy.dns.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Server is the DNS server address. If specified, this address overrides the
     * original one.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.Endpoint server = 1;</code>
     */
    protected $server = null;
    /**
     * Generated from protobuf field <code>uint32 user_level = 2;</code>
     */
    protected $user_level = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \V2ray\Core\Common\Net\Endpoint $server
     *           Server is the DNS server address. If specified, this address overrides the
     *           original one.
     *     @type int $user_level
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Dns\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Server is the DNS server address. If specified, this address overrides the
     * original one.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.Endpoint server = 1;</code>
     * @return \V2ray\Core\Common\Net\Endpoint|null
     */
    public function getServer()
    {
        return $this->server;
    }

    public function hasServer()
    {
        return isset($this->server);
    }

    public function clearServer()
    {
        unset($this->server);
    }

    /**
     * Server is the DNS server address. If specified, this address overrides the
     * original one.
     *
     * Generated from protobuf field <code>.v2ray.core.common.net.Endpoint server = 1;</code>
     * @param \V2ray\Core\Common\Net\Endpoint $var
     * @return $this
     */
    public function setServer($var)
    {
        GPBUtil::checkMessage($var, \V2ray\Core\Common\Net\Endpoint::class);
        $this->server = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 2;</code>
     * @return int
     */
    public function getUserLevel()
    {
        return $this->user_level;
    }

    /**
     * Generated from protobuf field <code>uint32 user_level = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setUserLevel($var)
    {
        GPBUtil::checkUint32($var);
        $this->user_level = $var;

        return $this;
    }

}

