<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/dns/config.proto

namespace V2ray\Core\App\Dns;

use UnexpectedValueException;

/**
 * Protobuf type <code>v2ray.core.app.dns.CacheStrategy</code>
 */
class CacheStrategy
{
    /**
     * Generated from protobuf enum <code>CacheEnabled = 0;</code>
     */
    const CacheEnabled = 0;
    /**
     * Generated from protobuf enum <code>CacheDisabled = 1;</code>
     */
    const CacheDisabled = 1;

    private static $valueToName = [
        self::CacheEnabled => 'CacheEnabled',
        self::CacheDisabled => 'CacheDisabled',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

