<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/http/config.proto

namespace V2ray\Core\Proxy\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * ClientConfig is the protobuf config for HTTP proxy client.
 *
 * Generated from protobuf message <code>v2ray.core.proxy.http.ClientConfig</code>
 */
class ClientConfig extends \Google\Protobuf\Internal\Message
{
    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     */
    private $server;
    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 2;</code>
     */
    protected $h1_skip_wait_for_reply = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\V2ray\Core\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $server
     *           Sever is a list of HTTP server addresses.
     *     @type bool $h1_skip_wait_for_reply
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proxy\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getServer()
    {
        return $this->server;
    }

    /**
     * Sever is a list of HTTP server addresses.
     *
     * Generated from protobuf field <code>repeated .v2ray.core.common.protocol.ServerEndpoint server = 1;</code>
     * @param array<\V2ray\Core\Common\Protocol\ServerEndpoint>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setServer($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Common\Protocol\ServerEndpoint::class);
        $this->server = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 2;</code>
     * @return bool
     */
    public function getH1SkipWaitForReply()
    {
        return $this->h1_skip_wait_for_reply;
    }

    /**
     * Generated from protobuf field <code>bool h1_skip_wait_for_reply = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setH1SkipWaitForReply($var)
    {
        GPBUtil::checkBool($var);
        $this->h1_skip_wait_for_reply = $var;

        return $this;
    }

}

