<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/request/assembly/config.proto

namespace GPBMetadata\Transport\Internet\Request\Assembly;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        \GPBMetadata\Google\Protobuf\Any::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAC\x03\x0A0transport/internet/request/assembly/config.proto\x12.v2ray.core.transport.internet.request.assembly\x1A\x19google/protobuf/any.proto\"w\x0A\x06Config\x12'\x0A\x09assembler\x18\x01 \x01(\x0B2\x14.google.protobuf.Any\x12*\x0A\x0Croundtripper\x18\x02 \x01(\x0B2\x14.google.protobuf.Any:\x18\x82\xB5\x18\x14\x0A\x09transport\x12\x07requestB\xAB\x01\x0A2com.v2ray.core.transport.internet.request.assemblyP\x01ZBgithub.com/v2fly/v2ray-core/v5/transport/internet/request/assembly\xAA\x02.V2Ray.Core.Transport.Internet.Request.Assemblyb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

