<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/dns/config.proto

namespace GPBMetadata\Proxy\Dns;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Destination::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAF\x02\x0A\x16proxy/dns/config.proto\x12\x14v2ray.core.proxy.dns\x1A common/protoext/extensions.proto\"M\x0A\x06Config\x12/\x0A\x06server\x18\x01 \x01(\x0B2\x1F.v2ray.core.common.net.Endpoint\x12\x12\x0A\x0Auser_level\x18\x02 \x01(\x0D\"'\x0A\x10SimplifiedConfig:\x13\x82\xB5\x18\x0F\x0A\x08outbound\x12\x03dnsB]\x0A\x18com.v2ray.core.proxy.dnsP\x01Z(github.com/v2fly/v2ray-core/v5/proxy/dns\xAA\x02\x14V2Ray.Core.Proxy.Dnsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

