<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/vmess/inbound/config.proto

namespace GPBMetadata\Proxy\Vmess\Inbound;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protocol\User::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC9\x04\x0A proxy/vmess/inbound/config.proto\x12\x1Ev2ray.core.proxy.vmess.inbound\x1A common/protoext/extensions.proto\"\x1A\x0A\x0CDetourConfig\x12\x0A\x0A\x02to\x18\x01 \x01(\x09\"0\x0A\x0DDefaultConfig\x12\x10\x0A\x08alter_id\x18\x01 \x01(\x0D\x12\x0D\x0A\x05level\x18\x02 \x01(\x0D\"\xD6\x01\x0A\x06Config\x12.\x0A\x04user\x18\x01 \x03(\x0B2 .v2ray.core.common.protocol.User\x12>\x0A\x07default\x18\x02 \x01(\x0B2-.v2ray.core.proxy.vmess.inbound.DefaultConfig\x12<\x0A\x06detour\x18\x03 \x01(\x0B2,.v2ray.core.proxy.vmess.inbound.DetourConfig\x12\x1E\x0A\x16secure_encryption_only\x18\x04 \x01(\x08\"7\x0A\x10SimplifiedConfig\x12\x0D\x0A\x05users\x18\x01 \x03(\x09:\x14\x82\xB5\x18\x10\x0A\x07inbound\x12\x05vmessB{\x0A\"com.v2ray.core.proxy.vmess.inboundP\x01Z2github.com/v2fly/v2ray-core/v5/proxy/vmess/inbound\xAA\x02\x1EV2Ray.Core.Proxy.Vmess.Inboundb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

