<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/network.proto

namespace V2ray\Core\Common\Net;

use UnexpectedValueException;

/**
 * Protobuf type <code>v2ray.core.common.net.Network</code>
 */
class Network
{
    /**
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Generated from protobuf enum <code>RawTCP = 1 [deprecated = true];</code>
     */
    const RawTCP = 1;
    /**
     * Generated from protobuf enum <code>TCP = 2;</code>
     */
    const TCP = 2;
    /**
     * Generated from protobuf enum <code>UDP = 3;</code>
     */
    const UDP = 3;
    /**
     * Generated from protobuf enum <code>UNIX = 4;</code>
     */
    const UNIX = 4;

    private static $valueToName = [
        self::Unknown => 'Unknown',
        self::RawTCP => 'RawTCP',
        self::TCP => 'TCP',
        self::UDP => 'UDP',
        self::UNIX => 'UNIX',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

