<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/net/network.proto

namespace V2ray\Core\Common\Net;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * NetworkList is a list of Networks.
 *
 * Generated from protobuf message <code>v2ray.core.common.net.NetworkList</code>
 */
class NetworkList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     */
    private $network;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<int>|\Google\Protobuf\Internal\RepeatedField $network
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Common\Net\Network::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getNetwork()
    {
        return $this->network;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.common.net.Network network = 1;</code>
     * @param array<int>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setNetwork($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::ENUM, \V2ray\Core\Common\Net\Network::class);
        $this->network = $arr;

        return $this;
    }

}

