<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/protocol/headers.proto

namespace GPBMetadata\Common\Protocol;

class Headers
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xEC\x02\x0A\x1Dcommon/protocol/headers.proto\x12\x1Av2ray.core.common.protocol\"H\x0A\x0ESecurityConfig\x126\x0A\x04type\x18\x01 \x01(\x0E2(.v2ray.core.common.protocol.SecurityType*l\x0A\x0CSecurityType\x12\x0B\x0A\x07UNKNOWN\x10\x00\x12\x0A\x0A\x06LEGACY\x10\x01\x12\x08\x0A\x04AUTO\x10\x02\x12\x0E\x0A\x0AAES128_GCM\x10\x03\x12\x15\x0A\x11CHACHA20_POLY1305\x10\x04\x12\x08\x0A\x04NONE\x10\x05\x12\x08\x0A\x04ZERO\x10\x06Bo\x0A\x1Ecom.v2ray.core.common.protocolP\x01Z.github.com/v2fly/v2ray-core/v5/common/protocol\xAA\x02\x1AV2Ray.Core.Common.Protocolb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

