<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/dokodemo/config.proto

namespace GPBMetadata\Proxy\Dokodemo;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Net\Address::initOnce();
        \GPBMetadata\Common\Net\Network::initOnce();
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAD\x05\x0A\x1Bproxy/dokodemo/config.proto\x12\x19v2ray.core.proxy.dokodemo\x1A\x18common/net/network.proto\x1A common/protoext/extensions.proto\"\xFC\x01\x0A\x06Config\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D\x12<\x0A\x0Cnetwork_list\x18\x03 \x01(\x0B2\".v2ray.core.common.net.NetworkListB\x02\x18\x01\x120\x0A\x08networks\x18\x07 \x03(\x0E2\x1E.v2ray.core.common.net.Network\x12\x13\x0A\x07timeout\x18\x04 \x01(\x0DB\x02\x18\x01\x12\x17\x0A\x0Ffollow_redirect\x18\x05 \x01(\x08\x12\x12\x0A\x0Auser_level\x18\x06 \x01(\x0D\"\xC1\x01\x0A\x10SimplifiedConfig\x122\x0A\x07address\x18\x01 \x01(\x0B2!.v2ray.core.common.net.IPOrDomain\x12\x0C\x0A\x04port\x18\x02 \x01(\x0D\x124\x0A\x08networks\x18\x03 \x01(\x0B2\".v2ray.core.common.net.NetworkList\x12\x17\x0A\x0Ffollow_redirect\x18\x04 \x01(\x08:\x1C\x82\xB5\x18\x18\x0A\x07inbound\x12\x0Ddokodemo-doorBl\x0A\x1Dcom.v2ray.core.proxy.dokodemoP\x01Z-github.com/v2fly/v2ray-core/v5/proxy/dokodemo\xAA\x02\x19V2Ray.Core.Proxy.Dokodemob\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

