<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proxy/freedom/config.proto

namespace V2ray\Core\Proxy\Freedom\Config;

use UnexpectedValueException;

/**
 * Protobuf type <code>v2ray.core.proxy.freedom.Config.DomainStrategy</code>
 */
class DomainStrategy
{
    /**
     * Generated from protobuf enum <code>AS_IS = 0;</code>
     */
    const AS_IS = 0;
    /**
     * Generated from protobuf enum <code>USE_IP = 1;</code>
     */
    const USE_IP = 1;
    /**
     * Generated from protobuf enum <code>USE_IP4 = 2;</code>
     */
    const USE_IP4 = 2;
    /**
     * Generated from protobuf enum <code>USE_IP6 = 3;</code>
     */
    const USE_IP6 = 3;

    private static $valueToName = [
        self::AS_IS => 'AS_IS',
        self::USE_IP => 'USE_IP',
        self::USE_IP4 => 'USE_IP4',
        self::USE_IP6 => 'USE_IP6',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

