<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/http/config.proto

namespace V2ray\Core\Transport\Internet\Http;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>v2ray.core.transport.internet.http.Config</code>
 */
class Config extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated string host = 1;</code>
     */
    private $host;
    /**
     * Generated from protobuf field <code>string path = 2;</code>
     */
    protected $path = '';
    /**
     * Generated from protobuf field <code>string method = 3;</code>
     */
    protected $method = '';
    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     */
    private $header;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $host
     *     @type string $path
     *     @type string $method
     *     @type array<\V2ray\Core\Transport\Internet\Headers\Http\Header>|\Google\Protobuf\Internal\RepeatedField $header
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Transport\Internet\Http\Config::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated string host = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHost()
    {
        return $this->host;
    }

    /**
     * Generated from protobuf field <code>repeated string host = 1;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHost($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->host = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @return string
     */
    public function getPath()
    {
        return $this->path;
    }

    /**
     * Generated from protobuf field <code>string path = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPath($var)
    {
        GPBUtil::checkString($var, True);
        $this->path = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string method = 3;</code>
     * @return string
     */
    public function getMethod()
    {
        return $this->method;
    }

    /**
     * Generated from protobuf field <code>string method = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMethod($var)
    {
        GPBUtil::checkString($var, True);
        $this->method = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getHeader()
    {
        return $this->header;
    }

    /**
     * Generated from protobuf field <code>repeated .v2ray.core.transport.internet.headers.http.Header header = 4;</code>
     * @param array<\V2ray\Core\Transport\Internet\Headers\Http\Header>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setHeader($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \V2ray\Core\Transport\Internet\Headers\Http\Header::class);
        $this->header = $arr;

        return $this;
    }

}

