<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: app/stats/config.proto

namespace GPBMetadata\App\Stats;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x85\x02\x0A\x16app/stats/config.proto\x12\x14v2ray.core.app.stats\"\x1E\x0A\x06Config:\x14\x82\xB5\x18\x10\x0A\x07service\x12\x05stats\"N\x0A\x0DChannelConfig\x12\x10\x0A\x08Blocking\x18\x01 \x01(\x08\x12\x17\x0A\x0FSubscriberLimit\x18\x02 \x01(\x05\x12\x12\x0A\x0ABufferSize\x18\x03 \x01(\x05B]\x0A\x18com.v2ray.core.app.statsP\x01Z(github.com/v2fly/v2ray-core/v5/app/stats\xAA\x02\x14V2Ray.Core.App.Statsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

