<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transport/internet/httpupgrade/config.proto

namespace GPBMetadata\Transport\Internet\Httpupgrade;

class Config
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Common\Protoext\Extensions::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xCF\x02\x0A+transport/internet/httpupgrade/config.proto\x121v2ray.core.transport.internet.request.httpupgrade\"F\x0A\x06Config\x12\x0C\x0A\x04path\x18\x01 \x01(\x09\x12\x0C\x0A\x04host\x18\x02 \x01(\x09: \x82\xB5\x18\x1C\x0A\x09transport\x12\x0Bhttpupgrade\x90\xFF)\x01B\x9C\x01\x0A-com.v2ray.core.transport.internet.httpupgradeP\x01Z=github.com/v2fly/v2ray-core/v5/transport/internet/httpupgrade\xAA\x02)V2Ray.Core.Transport.Internet.HttpUpgradeb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

